### ISSUE TITLE
Does it really remove Store (docs say 'yes', code says 'no')

### ISSUE THREAD

**Issue by GitTom** [Sycnex/Windows10Debloater#1]
The list of "Bloatware that is removed" includes "Store".  Is this different then the Microsoft Store? 

The code appears to whitelist the Windows Store (*Microsoft.WindowsStore*) so if they are the same thing then one should be changed.

For what it is worth, I have seen comments in various other cleanup scripts/discussions that say it is a bad idea to remove the store.

**Comment by Sycnex** [comment]
Wow, thanks for catching that! I didn't notice that the "Bloatware that is removed" had "Store" in it. 

The code doesn't remove the store since it is whitelisted and told to not remove it.

**Comment by Sycnex** [comment]
I'm going to remove it from that section.

**Comment by GitTom** [comment]
Also regarding the documentation...  you write “This comes in hand when setting up new Windows 10 machines…”

If this is just meant for new installations then you should probably be quite explicit about that - otherwise I think people will use it on existing, active, installs.  And I’m guessing it probably is just for new installations since your whitelist approach to uninstall probably means that it would uninstall user apps.

But I'm closing this because you addressed my issue, thanks!
