### ISSUE TITLE
Script removes any installed WSL Linux distros

### ISSUE THREAD

**Issue by beebop-Wiz** [Sycnex/Windows10Debloater#10]
I had Ubuntu installed on my desktop before I ran this script, and it wiped out all of my Linux data. I imagine this is because Linux distributions are installed from the Windows Store now, but an exception or warning or something should be added to prevent future data loss of this type.

**Comment by Sycnex** [comment]
Is it the Linux subsystem (bash) you're referring to?

**Comment by silasb** [comment]
Also confirmed that it removed my current Ubuntu install.  Needed to run the Windows Store install of Ubuntu to get it back.

**Comment by Sycnex** [comment]
Hi Silas,

Sorry about that. I didn't have the script checking for an existing
Ubuntu/WSL install at all.

I can add an exception, although I'd have to find out exactly what to check
for. Do you happen to have the name of the PackageName or anything related
to WSL? If not then no worries, I'm sure I can find out.

**Comment by silasb** [comment]
I'm not too worried about it. I took a look through the script and I think
`Get-AppxPackage -AllUsers` is returning

```
Name                   : CanonicalGroupLimited.UbuntuonWindows
Publisher              : CN=23596F84-C3EA-4CD8-A7DF-550DCE37BCD0
Architecture           : X64
ResourceId             :
Version                : 1604.2017.922.0
PackageFullName        :
CanonicalGroupLimited.UbuntuonWindows_1604.2017.922.0_x64__79rhkp1fndgsc
InstallLocation        : C:\Program
Files\WindowsApps\CanonicalGroupLimited.UbuntuonWindows_1604.2017.922.0_x64__79rhkp1fndgsc
IsFramework            : False
PackageFamilyName      : CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc
PublisherId            : 79rhkp1fndgsc
PackageUserInformation : {S-1-5-21-3667669488-3499114979-2985135006-1000
[SILAS-RYZEN-PC\silas]: Installed}
IsResourcePackage      : False
IsBundle               : False
IsDevelopmentMode      : False
IsPartiallyStaged      : False
SignatureKind          : Store
Status                 : Ok
```
EDIT:  urg Email replies don't support markdown :(

—Silas

**Comment by Sycnex** [comment]
Hi,

You should now find that CanonicalGroupLimited.UbuntuonWindows has been whitelisted and should no longer be removed.

**Comment by diVineProportion** [comment]
```
Name                   : KaliLinux.54290C8133FEE
Publisher              : CN=45FBC5C5-8DE5-4E85-AE6A-377002DA7605
Architecture           : X64
ResourceId             :
Version                : 1.1.7.0
PackageFullName        : KaliLinux.54290C8133FEE_1.1.7.0_x64__ey8k8hqnwqnmg
InstallLocation        : C:\Program Files\WindowsApps\KaliLinux.54290C8133FEE_1.1.7.0_x64__ey8k8hqnwqnmg
IsFramework            : False
PackageFamilyName      : KaliLinux.54290C8133FEE_ey8k8hqnwqnmg
PublisherId            : ey8k8hqnwqnmg
PackageUserInformation : {S-1-5-21-1234574612-1441434004-2252912779-1001 [root]: Installed}
IsResourcePackage      : False
IsBundle               : False
IsDevelopmentMode      : False
NonRemovable           : False
Dependencies           : {KaliLinux.54290C8133FEE_1.1.7.0_neutral_split.scale-150_ey8k8hqnwqnmg, KaliLinux.54290C8133FEE_1.1.7.0_neutral_split.scale-100_ey8k8hqnwqnmg,
                         KaliLinux.54290C8133FEE_1.1.7.0_neutral_split.scale-125_ey8k8hqnwqnmg}
IsPartiallyStaged      : False
SignatureKind          : Store
Status                 : Ok
```

As far as I can tell these are the only WSL 'distros' available in the store:
Ubuntu
Ubuntu 16.04 LTS
Ubuntu 18.04 LTS
SUSE Linux Enterprise Server 12
openSUSE Leap 42
Kali Linux

I don't know how to get the information without installing each one, so hopefully this helps!

**Comment by Merith-TK** [comment]
add another to the list, archlinux is now availiable
