### ISSUE TITLE
How to

### ISSUE THREAD

**Issue by kronikpillow** [Sycnex/Windows10Debloater#104]
Im not sure if im posting in the right place as im new to github, I have been using thus script for a long time but never figgured out how to run it pre user configuration, can anyone help?

**Comment by smoonlee** [comment]
Are you trying to use this in MDT or WDS or are you wanting to run it before a new user logs in

**Comment by Gray-0men** [comment]
Use the script now just right click and run as admin

You might get a prompt on the powershell windows asking if you want to run scripts from untrusted sources. Just press A and hit enter

**Comment by kronikpillow** [comment]
I am refering to is it possible to run it before user creation during windows install .. and what is needed to make it possible :D :) nor a MDT or a WDS ... yes when i use the script after user was created i find that it doesn't remove all the apps (some stay) and that it doesn't remove registry keys, i have to run a registry fixer after to fix it all

**Comment by smoonlee** [comment]
> ated i find that it doesn't remove all the apps (some stay) and that it doesn't remove registry keys, i hav

You have to run it before the user logs in... Run it on a local administrator account and then when a new user logs onto that device they wont get the Applications

**Comment by 4thehalibit** [comment]
> > ated i find that it doesn't remove all the apps (some stay) and that it doesn't remove registry keys, i hav
> 
> You have to run it before the user logs in... Run it on a local administrator account and then when a new user logs onto that device they wont get the Applications

if you run it after a user logs in will they get the apps 

example when setting up a new PC 
create acoount named work then install our remote software
i then log out log in as admin and run deblote GUI 
all users have individual logins so after i setup our companies programs will the tool be in affect for all users after that.

**Comment by kronikpillow** [comment]
you guys don't seem to understand my question, @smoonlee your answer kinda doesn't give me the answer as my question was how can i run it before a user logs in? I'm the user? There is no administrator account, my user is the administrator, it's a personal PC not a company ... I install my Windows 10 OS (latest iso), after instalation my system reboots i get a blue screen preparing my system, then it asks me for some details and asks me to setup a user via microsoft account or local user, I don't get to a login screen pre user creation

**Comment by Gray-0men** [comment]
Kronikpillow, basically after you create one user (after you go through the process of signing in or setting up a microsoft account or a local account) you run this script once and it'll debloat all the apps AS LONG as you don't have windows update running after the fresh install (basically run windows update first then this script) otherwise some apps get skipped

Every NEW user account after the first one you make will be without the apps, the first account you make on a fresh install it's unavoidable to NOT have apps but you get to watch them slowly disappear when you run the script for the first time.
