### ISSUE TITLE
Execution Policies Issues

### ISSUE THREAD

**Issue by LodanZark** [Sycnex/Windows10Debloater#105]
The script should execute` Set-ExecutionPolicy remoteSigned` and revert to `Set-ExecutionPolicy restricted` after finish the debloat tasks, in way to prevent the error  

> xxxx.ps1 cannot be loaded because running scripts is disabled on this system. For more information, see about_Execution_Policies at http://go.microsoft.com/fwlink/?LinkID=135170

**Comment by smoonlee** [comment]
You can manually do this on a system anyway?

**Comment by LodanZark** [comment]
Yes I can, this ticket was just a suggestion to turn the script more friendly to use, that's all.

**Comment by smoonlee** [comment]
Yes, but you cannot as you cant execute the script as it by default windows blocks the execution of scripts. unless you use: powershell.exe -executionpolicy remotesigned or bypass and the then file name.

**Comment by LodanZark** [comment]
I haven't realize that, thanks for the enlightenment.
Since it's something that cannot be done, I will close the ticket.
