### ISSUE TITLE
Make administrator elevation optional

### ISSUE THREAD

**Issue by abulgatz** [Sycnex/Windows10Debloater#106]
Can we make administrator elevation optional? A popup or parameter? If I run this script from a non-admin account and the script self-elevates (and I give it the password of an admin account), it doesn't actually remote the junk programs for the non-admin account.

**Comment by Sycnex** [comment]
It really works best when used with administrator permissions but I can add this in.

**Comment by Gray-0men** [comment]
It's not really optional, there's major parts of the code that won't work if you don't run it as admin

**Comment by abulgatz** [comment]
When I get a fresh Windows 10 computer, I:

1. Create a temporary user account and login
2. Run the Sysprep script with all flags
3. Create a local admin user account
4. Delete the temporary user account
5. Create the final non-admin user account and login

For this non-admin user account:

- All junk programs are gone (never installed) thanks to the sysprep script
- **Cortant** is enabled
- **Start suggestions** are enabled
- The **People icon** on the taskbar is showing
- Some **tracking** is enabled
- **Edge wants to take over as the PDF reader**

To fix the above, I run the `Windows10Debloater.ps1` script **as the current (non-admin) user**. Yes, the system-level changes that the script tries to make fail, but all of the above points are fixed.

If the script self-elevates, then the above points will **not** be fixed, as the script will be running as the wrong user account (the separate admin account).

**Comment by Gray-0men** [comment]
Temporary solution there is to just comment out the few lines of code about the admin check, it's the first bit of code in both scripts.

That is until we can make that optional

**Comment by Sycnex** [comment]
It is now optional to run as an Administrator @Gray-0men
