### ISSUE TITLE
Windows 10 Weather App

### ISSUE THREAD

**Issue by Xapixowy** [Sycnex/Windows10Debloater#107]
My Windows 10 MSN Weather App don't want to show actual weather status on start menu tile and lock screen. I tried to change localization settings, but they're locked. I think that Windows10Debloater causes the problem. Can you help me with that?

**Comment by Sycnex** [comment]
My script likely removed the dependencies that the Weather App requires, effectively killing its intended functionality.

**Comment by Xapixowy** [comment]
Is there a someway to restore it or add in Windows10Debloater with GUI possibility to change apps to uninstall? Something like tick menu called maybe blacklist, where i will be able to block apps from deleting.

P.S. Can you explain me, how the blacklist and whitelist works ("Remove Bloatware with/without Blacklist and Fix Whitelisted Apps")?

**Comment by jstnlth** [comment]
> P.S. Can you explain me, how the blacklist and whitelist works ("Remove Bloatware with/without Blacklist and Fix Whitelisted Apps")?
Remove All Bloatware: Dynamically find all of the Store apps on the computer, and delete all of them EXCEPT for the ones that are whitelisted.  (The blacklist is not used at all.)
Remove with blacklist: Delete all of the Store apps listed in the blacklist. The whitelist is ignored in this case.
I haven't really looked into the "fix whitelisted apps", but it doesn't do much and is a different whitelist than what is used with "Remove all Bloatware".

**Comment by Sycnex** [comment]
This was implemented as requested by @jstnlth
