### ISSUE TITLE
`Remove all bloatware` won't remove Network speed test and...

### ISSUE THREAD

**Issue by Sopor** [Sycnex/Windows10Debloater#109]
After running `Remove all bloatware` it seems to not remove `Network speed test` and `Xbox Live`. Any reason why these two are not removed?

I'm using the `Windows10DebloaterGUI.ps1` and Windows Version 1809 (OS Build 17763.379)

**Comment by Tmp341** [comment]
Have you checked log file?

**Comment by Sopor** [comment]
The log files only show when i removed OneDrive. I can't find the log files for the `Remove all bloatware` :(

**Comment by smoonlee** [comment]
Did you create a new account or use the same profile you can the de-bloater script on?

**Comment by Sopor** [comment]
The two files have the exact same date and time.. So this must be the file:

```
Initiating Sysprep
Starting Sysprep Fixes
Adding Registry key to Disable Windows Store Automatic Updates
Stopping InstallService
Setting InstallService Startup to Disabled
Removing bloatware apps.
Removing leftover bloatware registry keys.
Removing HKCR:\Extensions\ContractId\Windows.BackgroundTasks\PackageId\46928bounde.EclipseManager_2.2.4.51_neutral__a5h4egax66k6y from registry
Removing HKCR:\Extensions\ContractId\Windows.BackgroundTasks\PackageId\ActiproSoftwareLLC.562882FEEB491_2.6.18.18_neutral__24pqs290vpjk0 from registry
Removing HKCR:\Extensions\ContractId\Windows.BackgroundTasks\PackageId\Microsoft.MicrosoftOfficeHub_17.7909.7600.0_x64__8wekyb3d8bbwe from registry
Removing HKCR:\Extensions\ContractId\Windows.BackgroundTasks\PackageId\Microsoft.PPIProjection_10.0.15063.0_neutral_neutral_cw5n1h2txyewy from registry
Removing HKCR:\Extensions\ContractId\Windows.BackgroundTasks\PackageId\Microsoft.XboxGameCallableUI_1000.15063.0.0_neutral_neutral_cw5n1h2txyewy from registry
Removing HKCR:\Extensions\ContractId\Windows.BackgroundTasks\PackageId\Microsoft.XboxGameCallableUI_1000.16299.15.0_neutral_neutral_cw5n1h2txyewy from registry
Removing HKCR:\Extensions\ContractId\Windows.File\PackageId\ActiproSoftwareLLC.562882FEEB491_2.6.18.18_neutral__24pqs290vpjk0 from registry
Removing HKCR:\Extensions\ContractId\Windows.Launch\PackageId\46928bounde.EclipseManager_2.2.4.51_neutral__a5h4egax66k6y from registry
Removing HKCR:\Extensions\ContractId\Windows.Launch\PackageId\ActiproSoftwareLLC.562882FEEB491_2.6.18.18_neutral__24pqs290vpjk0 from registry
Removing HKCR:\Extensions\ContractId\Windows.Launch\PackageId\Microsoft.PPIProjection_10.0.15063.0_neutral_neutral_cw5n1h2txyewy from registry
Removing HKCR:\Extensions\ContractId\Windows.Launch\PackageId\Microsoft.XboxGameCallableUI_1000.15063.0.0_neutral_neutral_cw5n1h2txyewy from registry
Removing HKCR:\Extensions\ContractId\Windows.Launch\PackageId\Microsoft.XboxGameCallableUI_1000.16299.15.0_neutral_neutral_cw5n1h2txyewy from registry
Removing HKCR:\Extensions\ContractId\Windows.PreInstalledConfigTask\PackageId\Microsoft.MicrosoftOfficeHub_17.7909.7600.0_x64__8wekyb3d8bbwe from registry
Removing HKCR:\Extensions\ContractId\Windows.Protocol\PackageId\ActiproSoftwareLLC.562882FEEB491_2.6.18.18_neutral__24pqs290vpjk0 from registry
Removing HKCR:\Extensions\ContractId\Windows.Protocol\PackageId\Microsoft.PPIProjection_10.0.15063.0_neutral_neutral_cw5n1h2txyewy from registry
Removing HKCR:\Extensions\ContractId\Windows.Protocol\PackageId\Microsoft.XboxGameCallableUI_1000.15063.0.0_neutral_neutral_cw5n1h2txyewy from registry
Removing HKCR:\Extensions\ContractId\Windows.Protocol\PackageId\Microsoft.XboxGameCallableUI_1000.16299.15.0_neutral_neutral_cw5n1h2txyewy from registry
Removing HKCR:\Extensions\ContractId\Windows.ShareTarget\PackageId\ActiproSoftwareLLC.562882FEEB491_2.6.18.18_neutral__24pqs290vpjk0 from registry
Checking to see if any Whitelisted Apps were removed, and if so re-adding them.
Stopping telemetry, disabling unneccessary scheduled tasks, and preventing bloatware from returning.
Disabling Windows Feedback Experience program
Stopping Cortana from being used as part of your Windows Search Function
Stopping the Windows Feedback Experience program
Adding Registry key to prevent bloatware apps from returning
Setting Mixed Reality Portal value to 0 so that you can uninstall it in Settings
Disabling live tiles
Turning off Data Collection
Disabling People icon on Taskbar
Disabling suggestions on the Start Menu
Removing CloudStore from registry if it exists
Disabling scheduled tasks
Unpinning tiles from the Start Menu.
Unpinning all tiles from the start menu
Setting the 'InstallService' Windows service back to 'Started' and the Startup Type 'Automatic'.
Finished all tasks.
```

**Comment by smoonlee** [comment]
Did you modify the script prior to running it?

**Comment by Sopor** [comment]
No, it was totally original.

**Comment by Sycnex** [comment]
Try running the Windows10Debloater.ps1 and see if you have different results.

**Comment by Sopor** [comment]
I have already uninstalled everything. I can of course install a new Windows 10 in VM and try...

**Comment by gcormier** [comment]
Just ran this on a brand new 1809 Enterprise and the existing user did indeed have those, but a new user looks good.

![image](https://user-images.githubusercontent.com/8388983/55996968-0eca7380-5c87-11e9-9303-a1d119f85df2.png)

**Comment by smoonlee** [comment]
It applies to new users it doesn't debloat properly on exisiting profiles, best option is to run it on the reference image build before end users login

**Comment by Gray-0men** [comment]
One of the reasons it's not showing in the Log is that the code is write-output in the GUI version instead of write-host, 
I'll update the GUI to spit out logs better with Write-Host so we can see every command run and what it does. 

Also going make the log name more 'legible'

**Comment by Sycnex** [comment]
I’d suggest instead of using Write-Host or Write-Outpt, we should use Write-Verbose, and put $VerbosePreference = “Continue” at the top of the script, as this is far more detailed that the current logging that is in the code.

**Comment by Gray-0men** [comment]
idk why I didn't see this I would have replied earlier but I have some news on that, when I originally was going through and re writing all the write-output to write-host lines in the Windows10Debloater.ps1 file before I merged it I tried something out.

I was able to set a global verbose setting so that every command spit out a verbose output BUT that only worked well with the debloater.ps1 file and that the GUI version the verbose data just flat out didn't show up at all, I was actually using the $VerbosePreference = "Continue" in my script but abandoned it after I saw it wasn't working with the GUI version.

I'll do some digging, I feel like I backed up that test script somewhere and I can send you what the Windows10Debloater.ps1 will look like with the $VerbosePreference = "Continue" being used

I agree it's more detailed and we should at least switch to that with the non GUI version until I can see what's not working with the GUI version

**Comment by Sycnex** [comment]
@Sopor - Is this still an active issue?

**Comment by Sopor** [comment]
I have no idea. I haven't been using it for a long time. You are free to close it if you want :)
