### ISSUE TITLE
Add a way to make your own whitelist

### ISSUE THREAD

**Issue by jericjan** [Sycnex/Windows10Debloater#110]
There are some apps I don't like removed like Alarms & Clock and more Windows Store apps... Can you make it so that you can add apps to the whitelist?

**Comment by Sycnex** [comment]
Yup, I'll work on that. Are you okay with putting the apps you want whitelisted into a text file and then having the code read from that?

**Comment by dimqua** [comment]
Sounds good.

**Comment by jericjan** [comment]
I'm okay with that. As long as there's a list for the full program name for them like "Microsoft.Alarms" or something.

**Comment by 4thehalibit** [comment]
this will be awesome!!

**Comment by expphoto** [comment]
I like this idea too! I realized the script removed my alienware software :)

**Comment by hlb99** [comment]
I like this idea too! I'm using on Dell systems and it remove important applications from this manufacturer.

**Comment by mattreecebentley** [comment]
Are there any instructions online for constructing these whitelists/blacklists? Can't find a thing.

**Comment by Sycnex** [comment]
Another developer was awesome enough to implement this. When using the Allowlist/Blocklist, the checkmark means it is on the blocklist, and that it will be removed. @mattreecebentley
