### ISSUE TITLE
Missing lib

### ISSUE THREAD

**Issue by Yaksinikos** [Sycnex/Windows10Debloater#112]
Is it possible that somehow any of your debloat features is uninstalling "Microsoft Visual C++ 2010 Redistributable Package"?
Just asking because i got missing MSVCP100.dll after full debloat ...

P. S. Great Scripts & Tool in general :kissing_heart: you!

**Comment by Sycnex** [comment]
It is certainly possible. I'd suggest reinstalling "Microsoft Visual C++ 2010 Redistributable Package" from here: https://www.microsoft.com/en-us/Download/confirmation.aspx?id=14632

Sorry about that!
