### ISSUE TITLE
Running the debloat file give me parsing errors

### ISSUE THREAD

**Issue by SBanford** [Sycnex/Windows10Debloater#118]
When I run either the debloat script or the debloat with the GUI, I get parsing errors in Powershell. I have elevated the rights for running PS scripts as directed. Any thoughts on this? Thanks.

**Comment by Sycnex** [comment]
Did you copy the code directly from the web page? You will get parser errors when doing so. You need to download the files from here and run them correctly:

https://github.com/Sycnex/Windows10Debloater/archive/master.zip

**Comment by SBanford** [comment]
Why am I receiving email about the two years after I put in this support request?




Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
