### ISSUE TITLE
It looks like the script disables or removes remote desktop

### ISSUE THREAD

**Issue by boe1** [Sycnex/Windows10Debloater#120]
I couldn't find in the script where it does this but how do I prevent it from doing that?

**Comment by Sycnex** [comment]
It shouldn't be removing MSTSC (remote desktop connection). Did you download an RDP client from the Microsoft Store?

**Comment by boe1** [comment]
Line 73 says Microsoft.remotedestkop”

[cid:image001.png@01D4F7F5.9E12AFE0]

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by Sycnex** [comment]
Ah, my apologies. I think we were speaking of different applications. One thing you should do is comment it out, so you can put a # next to the line that you do not want removed.
