### ISSUE TITLE
Debloater Ready for 1903?

### ISSUE THREAD

**Issue by wbearr** [Sycnex/Windows10Debloater#129]
Hi.
I  will be installing Win 10 1903 soon on a new build. Should I wait for Debloater to be updated to reflect the changes in the new release? If so is there any projection on when it would be available and will that update be identified as such on the download page?
Thanks, Walter

**Comment by Sycnex** [comment]
It will be ready shortly. I am writing a new GUI, currently.

**Comment by PowderLinux** [comment]
Hey,
I see that there is Windows10DebloaterGUI.ps1 and Windows10DebloaterGUIOLD.ps1 now..
Is Windows10DebloaterGUI.ps1 the new GUI script for 1903? Thanks!

**Comment by guyowen** [comment]
When it is ready, could you please update the readme or somehow indicate that the scripts are 1903 ready. Thank you so much for all your efforts. Looking forward to the update. Thanks!

**Comment by DOspital** [comment]
Holy hell I love everything about this app. Thank you all for working on and creating this App! SCCM, WDS, MDT, SysPrep this tool has literally been the beano to my brainfarts. Again thank you all, Shots and pints on me!

**Comment by alanngo** [comment]
Can you close this issue? @Sycnex
