### ISSUE TITLE
More whitelist apps?

### ISSUE THREAD

**Issue by Blu3ish** [Sycnex/Windows10Debloater#13]
Hey Sycnex, and the GitHub community

I would like to be able to add whitelisted apps to my personal preference.

The problem is when i try to add them to the $whitelistedapps
and to the function fixwhitelistedapps the apps are removed anyway.

Could you please explain how to do so? Would be a live saver.

What ive tried is: 
•	Adding them  to the $whitelistedapps
•	Adding them to the function FixWhitelistedApps on line 4 of the start of the function
•	Adding them as another get-appxpackage  underneath FixWhitelistedApps

Result: on new users the apps are still nowhere to be found.

**Comment by Sycnex** [comment]
What packages are you adding to the Whitelisted apps function?

You have to run Get-AppXPackage and then identify the package name that you want to add. I can help you add it to the code for your preferences.

**Comment by Blu3ish** [comment]
apologies for the very late reply, I’ve added other apps by now, it was a typo that’s why they didn’t work at the first place.

**Comment by Blu3ish** [comment]
apologies for the very late reply, I’ve added other apps by now, it was a typo that’s why they didn’t work at the first place.
