### ISSUE TITLE
Can't access Internet 

### ISSUE THREAD

**Issue by arenaboy007** [Sycnex/Windows10Debloater#132]
After running all the scripts, I suddenly have no access to the internet even if the status is connected?

**Comment by Sycnex** [comment]
Check your internet drivers in your device manager and see if they need to be reinstalled. 

My script doesn’t uninstall any drivers, however. This is likely a coincidence.

**Comment by arenaboy007** [comment]
I fixed it. I created an outbound rule in the firewall settings for all programs.
