### ISSUE TITLE
URL based one-liner to run debloater GUI

### ISSUE THREAD

**Issue by foxfirecodes** [Sycnex/Windows10Debloater#134]
```powershell
iex ((New-Object System.Net.WebClient).DownloadString('https://git.io/debloat'))
```
Just thought this might be nice to add to the README as it is how I always run the debloater GUI now. The git.io link was just a link that I made using the free git.io URL shortener. You could, of course, instead use a raw GitHub link if that would be more secure in your opinion. 

I find this much simpler tho, and on older computers, it is quite laggy to copy & paste the debloater script into Powershell. This is almost instant, assuming a fast enough internet :)

**Comment by Sycnex** [comment]
You got it :D

**Comment by Sycnex** [comment]
Added it to the ReadMe.
