### ISSUE TITLE
Getting weird output on Win10 1709

### ISSUE THREAD

**Issue by evolutionxtinct** [Sycnex/Windows10Debloater#14]
I grabbed the .ZIP but noticed that the $whitelistapp has only a few apps...

#Removes AppxPackages
    #Credit to /u/GavinEke for a modified version of my whitelist code
    [regex]$WhitelistedApps = 'Microsoft.Paint3D|Microsoft.WindowsCalculator|Microsoft.WindowsStore|Microsoft.Windows.Photos|CanonicalGroupLimited.UbuntuonWindows'
    Get-AppxPackage -AllUsers | Where-Object {$_.Name -NotMatch $WhitelistedApps} | Remove-AppxPackage -ErrorAction SilentlyContinue
    Get-AppxProvisionedPackage -Online | Where-Object {$_.PackageName -NotMatch $WhitelistedApps} | Remove-AppxProvisionedPackage -Online -ErrorAction SilentlyContinue

I'm also noticing it finishes but doesn't really remove anything.... Am I running it wrong? I ran it in an elevated prompt it didn't seem to error out but noticed this in the output:

Uninstalling bloatware, please wait.

Path   :
Online : True

Path   :
Online : True

Path   :
Online : True

Path   :
Online : True

Path   :
Online : True

Seems to do this for every app it tries to uninstall.

**Comment by Sycnex** [comment]
Have you ran it more than once? How about after restating?

And that output looks fine.

**Comment by Sycnex** [comment]
I wanted to add:

As far as it goes, this mainly works for profiles that have not yet been created. You must run this script before you create the new profiles.

**Comment by Sycnex** [comment]
@evolutionxtinct May I close this?

**Comment by DeadlyMelqn** [comment]
How would you run this before creating any new profiles?? do you mean to create a new account after the one you have

**Comment by Blu3ish** [comment]
Here are a few examples how you would be able to create a local administrator account before you create a initial user account 

1. you can change the oobe (haven’t tried this) : https://searchenterprisedesktop.techtarget.com/tip/Create-a-hands-free-Windows-10-install-image-for-the-OOBE

2. Using a MDT Deployment to install windows for you. It uses the "administrator" account by default. you can use the script during the deployment process. while its installing all the needed applications as well. After that you can just script or manually disable the administrator account and create a user or use it as a domain computer. https://docs.microsoft.com/en-us/windows/deployment/deploy-windows-mdt/get-started-with-the-microsoft-deployment-toolkit

3. you can manually create a window 10 installation, run the script and sysprep it and after that use it for your needs.

4. you can create a user account, run the script, create a new user account for the actual user of the computer. and remove the account that made use of the script.


Hope this helps?

**Comment by DeadlyMelqn** [comment]
This helps a lot thank you! It was unclear to me what you ment at the time.

**Comment by evolutionxtinct** [comment]
Yes, thanks!

**Comment by Sycnex** [comment]
@Blu3ish Thanks for all of your help!

@DeadlyMelqn @evolutionxtinct Shall I close this issue?
