### ISSUE TITLE
Remove "OneDrive" environment variable

### ISSUE THREAD

**Issue by axieum** [Sycnex/Windows10Debloater#149]
When removing OneDrive from Windows 10, it should also remove the User Environment Variable that is left behind.

**Comment by Sycnex** [comment]
I added this as suggested. Code is as follows:

Remove-item env:OneDrive

**Comment by axieum** [comment]
Very nice! I literally just submitted a pull request #152 4 minutes too late 😂

**Comment by Sycnex** [comment]
Lol I was at my computer and figured I’d knock it out.
