### ISSUE TITLE
Workaround for using Windows10Debloater on ver. 1903 

### ISSUE THREAD

**Issue by LoVoltage** [Sycnex/Windows10Debloater#155]
Workaround for using Windows10Debloater with Windows 10 ver 1903

Fix: 
1. Open the Windows10DebloaterGUI.ps1 script and add a remark at the top.
2. Save the script with a new name with the .ps1 file extension to the same place as the original Windows10DebloaterGUI.ps1 file. 
3. Execute the script using the modified (new) file name, following the original instructions.

**Comment by Zyzto** [comment]
> Open the Windows10DebloaterGUI.ps1 script and add a remark at the top.

What do you mean by add remark? @FiveVolt

**Comment by chall324** [comment]
I think he means a comment,
haven't looked at the scripts yet, but it's either a # or / at the start of a line, to comment out that line

**Comment by nmhung1985** [comment]
Still doesn't work. The script doesn't show a box to ask if it should run as Administrator or not.

**Comment by cibolarobotics** [comment]
FYI: If I try to run the script, it kicks back errors. My workaround was to copy the entire script straight into powershell. Runs with no errors. I tested it only on the GUI script.

**Comment by SirYogiWan** [comment]
I removed the "<" before "#" in 1st line and copied direct into powershell
