### ISSUE TITLE
Windows 10 1703 hangs on reboot

### ISSUE THREAD

**Issue by Fejitatete** [Sycnex/Windows10Debloater#16]
After applying on 1703, windows can't reset normally : after closing services and shutdown the display the PC is not halted and stuck.

**Comment by Sycnex** [comment]
I haven't experienced this.

What else was the machine used for? Was it a clean install?

**Comment by Sycnex** [comment]
@Fejitatete Any updates?

**Comment by Sycnex** [comment]
Closing since I haven't heard an update.
