### ISSUE TITLE
Reinstalled removed apps

### ISSUE THREAD

**Issue by YenLegion** [Sycnex/Windows10Debloater#17]
I just noticed that some of the apps have been reinstalled. The date given for the reinstalled apps is a few days after I ran the script. Is it possible that Windows Update reinstalled these programs?

**Comment by Sycnex** [comment]
Hi,

Yes that is entirely possible. In fact, often enough you will find that
Windows Update will reinstall the apps.

Unfortunately there really is no permanent way to keep the apps removed
forever, unless you move to Windows 10 LTSB.

**Comment by Skatterbrainz** [comment]
I've been using the sysprep debloater at most of my customer engagements and so far it's worked very well and very consistently.  The only "updates" we've seen that do this (so far anyway) have been build upgrades.  None of the cumulative updates have reinstalled them as far as I've seen.  But the script could be re-applied if needed, using a variety of delivery means.

**Comment by Sycnex** [comment]
@YenLegion May I close this or would you like it to remain open?

**Comment by Sycnex** [comment]
Closing issue as I assume it is resolved.
