### ISSUE TITLE
Powershell Script hangs

### ISSUE THREAD

**Issue by scottbeau** [Sycnex/Windows10Debloater#18]
Hello Just ran this on a new Dell Machine Windows 10 OS 1709 and it hung after this point )see image) . I ran it another Machine and it ran just perfect . Any suggestions?? 
![capture](https://user-images.githubusercontent.com/38759352/39310666-037470c4-4939-11e8-88bd-b02ce047b452.PNG)
stions ??

**Comment by kdstart** [comment]
I'm having the same issue. Running in ISE. Hangs on Ln 494 Col 1. I've tried reverting and re-running the script and still hangs.

**Comment by Sycnex** [comment]
Hi,

I am unable to replicate this. How long did you let the script run for?

Also, @kdstart, the script you're using goes up to line 454. Can you try it again and send a transcript log located at C:\Windows10Debloater?

**Comment by kdstart** [comment]
I should be able to re-run this soon. I have a device updated to 1803 that I would like to test on as well.

**Comment by mrnr1** [comment]
I've had a bit of luck pressing `ENTER` when I notice that the script is hanging on a particular app. If that doesn't work I usually just CTRL + C to kill it and rerun it and the second time through it usually is able to get past it.

**Comment by kdstart** [comment]
@Sycnex, I have now run this in 1803 and am no longer having any issues. It ran flawlessly.

**Comment by Sycnex** [comment]
Fantastic, happy to hear that!
