### ISSUE TITLE
Windows Update not working after running debloater

### ISSUE THREAD

**Issue by rps54** [Sycnex/Windows10Debloater#180]
Windows10debloater is a very useful tool. Removed all unnecessary apps. However, Windows has a critical security update but I'm not able to run it. I get an error when I click on Windows Update. How do I enable Windows update, run it and then disable it again?

**Comment by rps54** [comment]
![WindowsUpdateError](https://user-images.githubusercontent.com/54685056/64036628-a559dd00-cb21-11e9-8692-84771d5a4d28.jpg)

**Comment by dschense** [comment]
I have the same problem with error 0x800703ed on all updates I want to start.
wanted to update 

.NET Framework 3.5 and 4.8 (KB4524100)
and
(KB4517389)

**Comment by VictorEmmanuels1223** [comment]
for me i tried updating, your organization does not give you permission update under group,
 policy etc. had the same problem. but what i like with the debloater, it never updated which allows my 32 bit and NTVM 16 bit old program to be working.

**Comment by rps54** [comment]
I tried using all options on the Debloater but couldn't restore the Windows Update service. Had to re-install Windows to install the latest Windows update. After reinstalling, I used the Debloater GUI to customize the software that I want to remove and some registry keys. Didn't run the entire script this time

**Comment by bitnboson** [comment]
Hello mates i got a kinda fix for this update issiue i think. I had the same problem, so i decided to install updates manually, so i looked up to download from microsoft (link:https://www.microsoft.com/en-us/software-download/windows10), click on "update now" butoon to download a small executable file. While you are running that software you can find the windows built-in updater begins to work properly. 
Hope this helps :) !
pls mention if you have any problem  with this.
