### ISSUE TITLE
Remove Some Components - Fails on other

### ISSUE THREAD

**Issue by Cash4Programming** [Sycnex/Windows10Debloater#19]
I just ran the script and it removed some item but not all :(  See attached transcript

[PowerShell_transcript.BLACK15.8ubCUUyB.20180427222703.txt](https://github.com/Sycnex/Windows10Debloater/files/1958972/PowerShell_transcript.BLACK15.8ubCUUyB.20180427222703.txt)

Thanks in advance,

**Comment by Sycnex** [comment]
Hi @Cash4Programming,

I see that there are errors showing "System.UnauthorizedAccessException,Microsoft.Windows.Appx.PackageManager.Commands.GetAppxPackageCommand
Get-AppxPackage : Access is denied.

Get-AppxProvisionedPackage : The requested operation requires elevation."

This means you did not run PowerShell as an Administrator when running this script. Try running PowerShell as an Administrator with this script and your issue will be resolved.

**Comment by Cash4Programming** [comment]
That fixed it.

Thanks!
