### ISSUE TITLE
Nvidia Control panel removed

### ISSUE THREAD

**Issue by Fi-xing** [Sycnex/Windows10Debloater#198]
Even if you reinstall your drivers it will not show up and you have to use Nvidia experience program instead of the normal control panel.

Can this be fixed please so it do not delete just that progam?

If you want Nvidia Experiance program it want you to add e-mail on their site and I do not want that when windows have a good normal program to control your Graphic card!

Only way to get it back is to login to windows store and get it that way, could not find that program anywhere else, if you did not want the Nvidia Experience program that is!

Except that I love the program and what it does!

**Comment by Sycnex** [comment]
I will add this in so that it does not remove it.

**Comment by Sycnex** [comment]
Added this to the whitelist. Please confirm it works.

**Comment by C1rdec** [comment]
I tried it yesterday and I can access my Nvidia Control panel

**Comment by Fi-xing** [comment]
Great, I haven't had the time to reinstall my computer but the person before say it works so you I just want to thank you and close this issue!
