### ISSUE TITLE
Start menu no longer works

### ISSUE THREAD

**Issue by KenHV** [Sycnex/Windows10Debloater#218]
I ran the GUI script on 1703 version. I selected yes on all options except for remove start pins. Now start menu no longer works on the account that I ran it on, search button still works though. Start menu works on another user account on the same machine.

I've tried reverting the changes, ran `sfc /scannow` and tried running this `Get-AppXPackage -AllUsers | Foreach {Add-AppxPackage -DisableDevelopmentMode -Register "$($_.InstallLocation)\AppXManifest.xml"}`. All to no avail.

**Comment by pixelchai** [comment]
I also have this problem. Trying to search for anything just results in an empty box (see picture)
![image](https://user-images.githubusercontent.com/30553505/73375958-8ae48500-42b4-11ea-87b1-49b9c60ada98.png)

I think it may be a problem with cortana? Can't find a way to reinstall cortana to confirm.

Anyway, it works on another user account

**Comment by MeetPing** [comment]
that's very strange.
I don't own the project but I looked at the code I'm just not sure it was exactly designed to break the start menu

**Comment by alexander-pick** [comment]
This happened due to a problem with the Microsoft Bing search feature and has nothing to do with this project.

**Comment by litecactus** [comment]
this can be closed
