### ISSUE TITLE
Semi-Cleanup Issues

### ISSUE THREAD

**Issue by Skatterbrainz** [Sycnex/Windows10Debloater#22]
We ran the script on Windows 10 1703 x64 Enterprise, and it seems to work, but the tiles are often left behind with labels showing the Appx ID values, rather than the ugly arrow symbols or icons.  They are broken tiles which do not respond to clicks.  This affects current user and new users which were not present (profiles) prior to running the script. Any recommendations?

**Comment by Sycnex** [comment]
I've been told of this issue in the past and I don't have an answer for it, unfortunately.

**Comment by xsisbest** [comment]
You will need to push a custom start menu layout using group policy or as a task sequence during your deployment. It's pretty easy to do and takes care of the arrow issue.
Here is a link to a page that explains how. https://bjtechnews.org/2016/04/deploying-a-customized-windows-10-start-menu-with-mdt-2013/
