### ISSUE TITLE
Great job!

### ISSUE THREAD

**Issue by amithiel** [Sycnex/Windows10Debloater#223]
Hey there, 

I just had to come here to thank you! I just clean installed my windows machine, and i can't thank you enough for this script! everything worked as it should, and i'm really enjoying this clean and smooth experience. Thanks for your work man, really aprecciate you take the time to care about us :)
cheers and have a nice day

**Comment by Sycnex** [comment]
I'm happy you enjoy it! And also credit to other collaborators as well :D
