### ISSUE TITLE
Function 'DebloatAll': $Nonremovable ...

### ISSUE THREAD

**Issue by madworm** [Sycnex/Windows10Debloater#227]
In commit 'c6b62f99a65c8a76' the variable $Nonremovable was changed by "|*Nvidia*" and now reads:

... Microsoft.Services.Store.Engagement|Microsoft.UI.Xaml.2.0'|*Nvidia*

Should the tick-mark not be after |*Nvidia* ?

**Comment by madworm** [comment]
https://github.com/Sycnex/Windows10Debloater/commit/c6b62f99a65c8a7680b78738629b8b3c9501d28e

**Comment by Sycnex** [comment]
This is now fixed.
