### ISSUE TITLE
Script says it does not remove Calculator and Microsoft Store

### ISSUE THREAD

**Issue by B3S3SS3N** [Sycnex/Windows10Debloater#23]
It in fact does

**Comment by B3S3SS3N** [comment]
I just ran Get-AppxPackage -allusers Microsoft.WindowsStore | Foreach {Add-AppxPackage -DisableDevelopmentMode -Register "$($_.InstallLocation)\AppXManifest.xml"}
to get it back, but figured I'd let you know

**Comment by Sycnex** [comment]
Interesting...It really should not be. What build of Windows 10 are you running it on? Is it a brand new profile or an older one?

**Comment by xsisbest** [comment]
I've ran this script many times and it has never removed calculator or store. Just my experience.

**Comment by Sycnex** [comment]
@B3S3SS3N  What version of Windows?

**Comment by Blu3ish** [comment]
@B3S3SS3N Only at the user you’re using the script on. But since it cannot change windows 10 start menu items you should consider creating a new user.

**Comment by shufty** [comment]
Hey mate, I'm having this issue to, it appears the white list in the code isnt being adhered to.

I need the photo app, which is in the whitelist, but it still gets uninstalled. I even tried adding the full name to the white list:

[regex]$WhitelistedApps = 'Microsoft.WindowsCalculator|Microsoft.WindowsStore|Microsoft.Windows.Photos_2017.37071.16410.0_x64__8wekyb3d8bbwe'

Still uninstalls it.

Just noticed it's uninstalled the Calculator and Store too...

This is on Windows 10 Build 16299

**Comment by B3S3SS3N** [comment]
@Sycnex my god, my notifications were off on this email, sorry for leaving this hanging. I was running 16299.431

@Blu3ish ill at the user and test it and let this thread know

**Comment by Sycnex** [comment]
@B3S3SS3N Give it another shot.

**Comment by B3S3SS3N** [comment]
Ill giver a shot this weekend as advised in the thread and let you know.

Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by Sycnex** [comment]
Hi @B3S3SS3N, do you have an update for this?

**Comment by B3S3SS3N** [comment]
Hi,

I did not forget, I have literally touched zero of my computers at home to test. I have told my wife to remind me to test it while I am in Peace River Thursday to Sunday.

My apologies.

Regards,
Cam

**Comment by Sycnex** [comment]
Sounds good! And no worries at all. I was just checking :)

**Comment by B3S3SS3N** [comment]
Hi @Sycnex I ran the debloater updated script from 19 days ago and it ran flawlessly now :)
