### ISSUE TITLE
High disk usage from "System" process

### ISSUE THREAD

**Issue by Brainsh0ter** [Sycnex/Windows10Debloater#233]
So i did everything in the video.. Everything is working fine except when i am trying to play COD Warzone the "System" process is the only process while im playing that has high disk usage and that results to stuttering while i am playing!
This did not occur before the changes i made..
Does anyone have any kind of solution or advice?
Thank you in advance!

**Comment by johnneijzen** [comment]
hmm hopefully it is not under system interrupts if that is case then there is hardware level error

**Comment by Brainsh0ter** [comment]
So to give more details, i do not think (and certainly hope) this is the process you are talking about. This is the 'System' Process i am talking about:
![System Process](https://user-images.githubusercontent.com/61632273/77407406-c08e8180-6dbe-11ea-8a22-70ac4ebe7c44.png)

and this is its file location
![Screenshot_3](https://user-images.githubusercontent.com/61632273/77407461-d439e800-6dbe-11ea-9025-1de42616c910.png)

The 1st solution i tried and seemed to work was a program called TimerResolution which made my computer's Current Timer Resolution from 1ms to 0.5ms. (Timer Resolution does not work)

**Comment by Brainsh0ter** [comment]
So i do not recall having these "Parent" permissions and i am pretty sure it is from the debloater since i found out about them since i could not enter the Windows Apps Folder. 
![Screenshot_1](https://user-images.githubusercontent.com/61632273/77553178-25300600-6ebd-11ea-84ec-4ec13b8a7a04.png)

Can someone please help me remove them cause i am trying to solve this stuttering problem 3 days now..
Thanks in advance!

**Comment by johnneijzen** [comment]
hmm so far i don't think it debloater at least no one else has report this issue so far and i even testing on other machine to see if something similar to this issue will happen but nothing wrong happened and that parent permission is not debloater based on script it never change it permission it use powershell Remove-AppxPackage to remove apps also windows apps folder is locked by os by default because it sandbox area for apps.

i wonder did you had any windows updates  or drivers updates happen before the issue?

**Comment by Brainsh0ter** [comment]
Right before the issue, no... After the issue i tried to access a manual restore point i created which came to be corrupted (i left it for an hour). After that since the in-game stuttering persisted i made a clean installation of the Nvidia Drivers (removed with DDU) and after i saw that did not work either i did a windows update. Also between all these steps i have used "sfc /scannow" and the "DISM RestoreHealth". Well from some more digging i did, COD Warzone has the option to show CPU and GPU Time and while the Frame spikes, stuttering was occuring, it was when the CPU Time was going >50ms from ~10ms where it usually stands.

John thank you for testing but it seems i might have to do a clean installation of Windows and see if that fixes it. The problem might not be the debloater but maybe something else..

**Comment by Brainsh0ter** [comment]
Ok guys, i reinstalled my Windows while keeping files and apps and everything seems to work fine.
If you want you can delete this thread since it was a personal issue that was not resolved.
