### ISSUE TITLE
Hey, i asked if this would couse any harm in Reddit and had some negative feedback.

### ISSUE THREAD

**Issue by JFMugen** [Sycnex/Windows10Debloater#235]
This is the post

https://old.reddit.com/r/windows/comments/fr5678/what_do_you_think_about_this_debloater/

I wanted to ask here as well, since i think it is fairer to ask both :)

Is it possible to encounter some problems while updating Windows etc? 

(Sorry if this is a repost, i searched but didn't see something like this)

Thanks :)

**Comment by Sycnex** [comment]
I myself have tested this on well over a dozen machines and have never encountered a single problem. My friends use it at their shops and workplaces without any issues. However, there is the occasional issue that someone experiences and I have absolutely no idea how it happens, as the code doesn’t remove or touch anything critical to the operability of Windows. 

The comment stating that it touches services/registry keys/app packages is correct, however, in new Feature updates of windows (e.g. 1903/1909) those same registry keys/services/apps are reinstalled anyways. Removing them does not hurt anything. 

But at the same time, YMMV.

**Comment by JFMugen** [comment]
Thank you for the answer :) I think that was a clear explanation.

**Comment by Faty100** [comment]
Hey i have tried the GUI on many machines myself and the custom remove doesnt seem to work at all unless i run it directly from the dcript itself without using the GUI.

Can you try the GUI yourself on 1909 and see if it works for you. Please use the custom removal option, check mark a few option and save it and let me know what happens.

It use to work before but now it doesnt. All it does for me is just scans all bloatware in a second and says finished but nothing was removed.


Sent from Outlook Mobile<https://aka.ms/blhgte>
________________________________

**Comment by Faty100** [comment]
By any chance did you get time to try this?
