### ISSUE TITLE
Errors when completing MDT - No start menu search due to copyprofile

### ISSUE THREAD

**Issue by xsisbest** [Sycnex/Windows10Debloater#24]
Thank you so much for this script. It does everything I need it to for sure.
I do have one question though as every time I get done with deployment it gives me the results and it shows 26 errors. All seem to come from the script but I don't have a clue to know which one's it's referencing. I am doing a clean build of v1803 right now to see if it results in the same but it doesn't have any effects on the install just not sure why I get errors. I am also removing the edge pdf parameter as I pretty much disable edge any way. Would love to clean them up if possible. Here is a screenshot of the errors. Thanks again for your hard work!
![mdt error1](https://user-images.githubusercontent.com/39020284/39671144-a6012bda-50c7-11e8-9ed1-6870b5a5eaf5.jpg)

**Comment by xsisbest** [comment]
I wanted to give an update. I updated my iso to v 1803 of windows 10 pro and now I only get 22 errors in the script but one issue I'm having is I can't search from the start menu on my new accounts. The built in administrator account is fine but any new accounts that are created, when I push the windows button and type calc for instance, calculator doesn't popup. I have to find it in the menu. Same for any app but with 1709 the script didn't effect this. Not sure why it would but something to be aware of I suppose with the newest build.
I also removed that line about XboxGameSaveTaskLogon so we'll see if that makes most of those errors go away. the ones at the bottom were apps not removed from my applications.xml in my control folder in mdt.

**Comment by xsisbest** [comment]
Well, after syspreping my image several times and creating a new wim a few times, as well as trying another script... I'm convinced it's nothing to do with your script. I still can't search from other newly created accounts but can from admin account. I think it's just going to take some troubleshooting to figure it out but I do rename the Edge folder in C:\windows\Systemapps to "old" at the end so edge doesn't run but I did that in 1703 too. Not sure what else could be causing it as Cortana is untouched.

**Comment by xsisbest** [comment]
So I've finally figured out all my issues. I resolved all my errors by removing the lines with EdgePDF throughout your script and just left that part out. 
The issue with the start menu search not working was due to the copyprofile=true in my unattend.xml file. For some reason in 1703 and now 1803 it breaks the search. The solution for me was to run Litetouch.vbs and let it run sysprep and capture my wim file for my operating system. 
Then I used 7zip to open the wim file and delete these folders and file. You can also use a task sequence doing a command line for a batch file if you like: (you'll need to enable view hidden files and folder and view operating system files in folder options)

@echo off
rmdir C:\users\Administrator\Appdata\Local\Microsoft\Windows\INetCache
rmdir C:\users\Administrator\Appdata\Local\Microsoft\Windows\WebCache
del C:\users\Administrator\Appdata\Local\Microsoft\Windows\WebCacheLock.dat

exit

**Comment by Sycnex** [comment]
My apologies for the late response. 

Fantastic troubleshooting and analysis. I've always wondered exactly how the start menu search breaks and I can even use this at work as well. Thanks for that.

Are you having issues with the scrip otherwise?

**Comment by xsisbest** [comment]
The only issue I was having was the telling Edge not to be the default for PDF's StopEdgePDF so I took it out. After that I got rid of all errors I was having. I have yet to test this with v1803 again but i will be soon. I'm pretty sure the same issue with search will fix it on that version as well. Thanks again for your awesome work!

**Comment by Sycnex** [comment]
I do my best!
