### ISSUE TITLE
SysPrep Script causes errors in MDT

### ISSUE THREAD

**Issue by hessercan** [Sycnex/Windows10Debloater#240]
Stop-Process : Cannot bind parameter 'InputObject'. Cannot convert the "Explorer.exe" value of type "System.String" to type "System.Diagnostics.Process". Line:179, char:19

**Comment by Blu3ish** [comment]
Windows10SysprepDebloater.ps1
Line 179 char 19

Stop-Process explorer.exe -Force doesnt work. (check it at powershell)
Without the -name aurgument it tries to stop a PID

Surgested solution: edit it too:

Stop-Process -Name explorer -Force
