### ISSUE TITLE
Can't access Minecraft

### ISSUE THREAD

**Issue by Tatsze** [Sycnex/Windows10Debloater#248]
I used the remove all bloatware option, and all the other options (remove onedrive, remove edge as pdf default viewer...) and now I can't sign in into my Minecraft account (this is Minecraft Bedrock by the way, the one that you download from the Microsoft Store). Then I used the "Reset" button. Used the GUI version of this utility. I tried to uncheck all the Xbox or gaming related things in the "Customize blacklist" option but when I finished and clicked "Save blacklist settings" it didn't save it, tried a couple times but didn't work. Then I used the "Remove without blacklist" or something and tried to go into Minecraft but it didn't work either.

Also tried to install Xbox companion app, Xbox beta and Xbox game bar from the Microsoft Store but it didn't work either.

**Comment by JF-SD** [comment]
Also having this issue

**Comment by Tatsze** [comment]
> Also having this issue

Yeah, and it is kinda sad actually. I've tried a couple things but didn't work.
By the way, I'm open to write more info about the issue if the developer wants me to.

**Comment by JF-SD** [comment]
> 
> 
> > Also having this issue
> 
> Yeah, and it is kinda sad actually. I've tried a couple things but didn't work.
> By the way, I'm open to write more info about the issue if the developer wants me to.

I managed to fix it, install the xbox app if you dont have it, for me it told me that i was missing somne of its dependencies, i installed them and then minecraf worked just fine, hope this helps!

**Comment by Tatsze** [comment]
> I managed to fix it, install the xbox app if you dont have it, for me it told me that i was missing somne of its dependencies, i installed them and then minecraf worked just fine, hope this helps!

OMG!! It works!!! I didn't install the Xbox game bar and the Center of feedback (my language is Spanish so it maybe isn't the correct translation) and it still works!! :-D You're my savior!!! Thank you, kind gentleman 👍

**Comment by CapinWinky** [comment]
I just dealt with this same issue. Installing and then launching the `Xbox (beta)` app from the Microsoft Store directs you to fix dependencies in the settings menu. The ONLY dependency you need is the `Microsoft.XboxIdentityProvider`. I'm fairly certain you don't actually need the Xbox app, but haven't checked that. 

If you wiped out the microsoft store app, you can bring it back in PowerShell with:

`Get-AppxPackage -allusers Microsoft.WindowsStore | Foreach {Add-AppxPackage -DisableDevelopmentMode -Register "$($_.InstallLocation)\AppXManifest.xml"}`

This is an entry in the custom blacklist, so simply select not to remove it. FYI, the custom list does save as `custom-list.ps1` though the GUI gives no indication that has succeeded.
