### ISSUE TITLE
Windows store (game) apps

### ISSUE THREAD

**Issue by Blu3ish** [Sycnex/Windows10Debloater#25]
So, I’ve got another issue I noticed but first of all I want to thank you for your work since the script is just awesome!

the store is not uninstalled which is fine and I wouldn’t want it to be uninstalled. My issue lays that there are often there are apps that require Xbox to be installed to work, almost always games. Since I do not want bloatware but all of my functionality to work I am massaging you once again.

I cannot find what apps are required to run Xbox games on google so I tried some myself:

What I first tried is adding the following apps to the white list: Microsoft.XboxGameOverlay, Microsoft.XboxGamingOverlay, Microsoft.Services.Store.Engagement, Microsoft.XboxSpeechToTextOverlay, Microsoft.Xbox.TCUI.

I confirmed the apps where on the system after installation and tried to install a game to test. Unfortunately, it made no difference so I tried removing the removal of the scheduled tasks because I didn’t know what they did just for testing but that didn’t change anything.

So how I test is installing this app: https://www.microsoft.com/en-us/store/p/age-of-empires-castle-siege/9wzdncrfjb5l 
When it says connection error (it doesn’t give an error without running this script on my deployment) it means it’s still missing an app or multiple apps.

I hope you can help me out, thanks in advance.

**Comment by xsisbest** [comment]
Just go through the script and remove anything that says xbox in it so it doesn't uninstall anything xbox related.

**Comment by Blu3ish** [comment]
That’s what I tried, Microsoft.XboxGamingOverlay, Microsoft.XboxSpeechToTextOverlay, Microsoft.Xbox.TCUI. are the only Xbox apps and when they are in the whitelist the game('s) still don’t work. Also searching for "Xbox" in the script and removing the removal of the scheduled tasks doesn’t work neither. But thanks for your fast reaction.

**Comment by Sycnex** [comment]
Hello, I actually experience the same thing. From my testing it seems that you lose the rest of the Xbox Appxpackages/appxprovisionedpackages once they're removed and it doesn't look like they can be re-added, unfortunately.

**Comment by Blu3ish** [comment]
So, is there a possibility that I can prevent removal in the first place? wouldn’t that solve it?
Of course, I wouldn’t like bloatware to be on my computers, but I could make a difference between Windows 10 Home and Pro since pro is more for those who use their computer inside domains or as hypervisor anyway and the home users just basically use it for basic use and games.

**Comment by Blu3ish** [comment]
So I’ve figured it out. The following apps have to be added to the whitelist or have to be reinstalled to the system to make Xbox connected apps available again. :

Microsoft.XboxGamingOverlay
Microsoft.XboxIdentityProvider
Microsoft.Xbox.TCUI

If installed it works perfectly fine again.

**Comment by Sycnex** [comment]
I can make it so that those are not removed.

**Comment by Sycnex** [comment]
I updated the scripts so that those aren't removed.
