### ISSUE TITLE
Is there a way to run on an offline image?

### ISSUE THREAD

**Issue by Vicfixx** [Sycnex/Windows10Debloater#253]
Is there a way to run on an offline image? I want to debloat a windows 10 install image. I have the image mounted, but there is no option to select the image I want to debloat.
I tried adding      -Path "c:\1 Mount"   in the script, but no luck

**Comment by strotee** [comment]
Look at https://github.com/DrEmpiricism/Optimize-Offline.

**Comment by Vicfixx** [comment]
Thanks for the tip. Just finished and I am going to test it. You wouldnt happen to know how I can remove upgrade option and remove files that are not in the ESD? I desperatly want to get the install to fit on a 1.4 gb mini DVD.
