### ISSUE TITLE
Suggestion: app cleanup on current user

### ISSUE THREAD

**Issue by abulgatz** [Sycnex/Windows10Debloater#26]
I'd recommend adding this line:

`Get-AppxPackage | Where-Object {$_.Name -NotMatch $WhitelistedApps} | Remove-AppxPackage -ErrorAction SilentlyContinue`

Right after this line:

`Get-AppxPackage -AllUsers | Where-Object {$_.Name -NotMatch $WhitelistedApps} | Remove-AppxPackage -ErrorAction SilentlyContinue`

This will remove apps from the currently logged in user account.

**Comment by Sycnex** [comment]
Done. Thanks.

**Comment by abulgatz** [comment]
Thanks, but looking at the script and the git history I don't see that you've added this line? Did you push the changes?
