### ISSUE TITLE
Awesome-ness

### ISSUE THREAD

**Issue by fredenocs** [Sycnex/Windows10Debloater#29]
Nice work, thank you.  Doing it as-is in hyper-V, then reviewing it afterwards. 

Can you add/remove the "most used" section.  Maybe a prompt, eh?
Ridding of get help, hp smart, mixed reality portal/viewer, onedrive returns, when going into add/remove asking to update, then just happens, ricoh driver utility, windows defender security center, connect.

Excuse me for any errors.  I installed 1709, all was fine, then a update occurred and seemed to bring back some of these apps mentioned above.

**Comment by Sycnex** [comment]
@fredenocs Can you please clarify what you mean by "Can you add/remove the "most used" section. Maybe a prompt, eh?"?

Large updates to the Windows OS will bring back bloatware, which is expected, and unfortunate. I am unable to completely prevent bloatware but at least I can remove what is there in the current instance.

**Comment by fredenocs** [comment]
In the start menu an option to remove the most used section. I understand it cannot be 100%.  But just wanted share my experiences.  Any chance for the above items to be added.

**Comment by Sycnex** [comment]
Oh I see, you're asking for somewhat of a blacklist to specify specifically
what you'd like removed. I was thinking about adding one to compliment the
whitelist that I currently have.

Give me some time and I will add that in.

**Comment by Sycnex** [comment]
Windows Defender is built into the OS so I cannot remove it, unfortunately.

**Comment by fredenocs** [comment]
Far as me testing this after each version of window updates, seem to remove the newly added programs.
Running multiple times, doesn't seem to impact anything.

**Comment by Sycnex** [comment]
Yeah, running it more than once won't have any extra benefits.

**Comment by Sycnex** [comment]
Get help should be getting removed, but I don't necessarily want to add an option to remove HP Smart in case someone actually uses that utility. As for the most used section; I believe this is a core windows function that I cannot necessarily modify.
