### ISSUE TITLE
Explorer.exe acting weird

### ISSUE THREAD

**Issue by ghost** [Sycnex/Windows10Debloater#293]
Hey there! after running the script, I noticed my explorer.exe was acting different, I just have to click something once now and it opens, as well as everything is underlined, wondering if there was anything I could do to fix this, below is an attacted video

>> https://streamable.com/t44tn8 <<

that clip is just me clicking once

**Comment by DoubleDot** [comment]
Looks like your PC is in tablet mode?

**Comment by ghost** [comment]
I don't know, everything else is acting fine just explorer.exe.. Will have a look at it though! thanks for the response!

**Comment by woozy404** [comment]
Turns out it wasn't. Still haven't found out whats wrong

**Comment by ghost** [comment]
Fixed the error.. for anyone else having this issue read this thread:
https://www.tenforums.com/general-support/80062-everything-underlined.html
