### ISSUE TITLE
Microsoft Store

### ISSUE THREAD

**Issue by iPhoneMaster** [Sycnex/Windows10Debloater#31]
If Microsoft Store gets removed by the script is there a way to restore it?  I've looked all over the web and tried the various PowerShell commands, but I can't seem to find a way to get the Microsoft Store back.

**Comment by fredenocs** [comment]
Id' say revert it back, run the script as it prompts to revert changes.
OR
Edit the script, search the script for "store" and command is there

**Comment by iPhoneMaster** [comment]
I've tried both options with no luck. The files for the Store from the C:\Program Files\WindowsApps are completely gone and the registry items are also.  So I'm not understanding how the script or commands from the script can restore the store.

**Comment by Sycnex** [comment]
@iPhoneMaster I'm surprised the revert option didn't help you as that's what I use in my testing.

Unfortunately you may need to do a system restore.

**Comment by 007craft** [comment]
Enter this in powershell

Get-AppXPackage | Foreach {Add-AppxPackage -DisableDevelopmentMode -Register "$($_.InstallLocation)\AppXManifest.xml"}

It will restore everything, including Microsoft Store.  The whitelist feature on this script doesnt work.  It removes EVERYTHING.  Which is not good.

**Comment by Sycnex** [comment]
@007craft Interesting that you say the whitelist doesn't work. I haven't had any issues with it. What version of Windows 10 are you running?

**Comment by iPhoneMaster** [comment]
@007craft I've tried that multiple times and it never restores the MS Store because the entire Microsoft.WindowsStore_11804.1001.10.0_x64 folder is missing.  The folder seems to get removed during the initial build of the OS before a user ever logs in.  I've even tried copying that folder from another working PC and MS Store will try to start but then crashes.

**Comment by iPhoneMaster** [comment]
@Sycnex I'm running Windows 10 Pro build 17134.1

**Comment by Sycnex** [comment]
I will write up a quick fix for this. So sorry about that! I haven't experienced that.

**Comment by Sycnex** [comment]
@iPhoneMaster I found an article online to resolve your issue. Look here:

https://superuser.com/questions/949112/restore-microsoft-store-application-in-windows-10

And since they fail to even open, read Microsoft's guide here: https://support.microsoft.com/en-us/help/2798317/microsoft-store-apps-fail-to-start-if-default-registry-or-file-permiss

**Comment by iPhoneMaster** [comment]
@Sycnex No worries!  The link you provided allowed me to restore the missing folders from C:\program files\windowsapps and re-register the MS Store in Windows.  I would consider this issue resolved. Thanks again Sycnex! :-)
