### ISSUE TITLE
Deleted Question.

### ISSUE THREAD

**Issue by byronbytes** [Sycnex/Windows10Debloater#310]
Deleted Question.

**Comment by jebjordan** [comment]
.. why does this need to be asked?
It's under the MIT license so technically you can literally do whatever you want with it as long as you follow the conditions

**Comment by DrSaad77** [comment]
> .. why does this need to be asked?
> It's under the MIT license so technically you can literally do whatever you want with it as long as you follow the conditions

you right, but it is also polite from him to ask...

**Comment by Sycnex** [comment]
I appreciate you asking! But yes, what @jebjordan said.
