### ISSUE TITLE
Some "apps" aren't exactly Bloatware.

### ISSUE THREAD

**Issue by ExacoMvm** [Sycnex/Windows10Debloater#317]
**Alarms & Clock** ( Semi-Bloatware - Replaced by Smartphone ) - It's useful if you keep your PC running 24/7 but ofcourse Phone is always best unless you need alarm on your big ass speakers.
**Weather** ( Semi-Bloatware ) - Actually useful, quicker to check than lets say in a browser or smartphone especially if using w/ Search box enabled ( LMB -> "W" -> LMB -> Done ).
**Camera** - Useful to check if cam is working without calling anyone or risking privacy on "Online Cam Test".
**Sound Recorder** - Same stuff as with camera except for a mic.

Other than that great script!

**Comment by neelkarma** [comment]
If you aren't happy with the default settings, you can make a whitelist that preserves the apps you want to preserve.
