### ISSUE TITLE
Paint3d removed even though whitelisted Win 10 Education 1803 Build 17134.112

### ISSUE THREAD

**Issue by gusrice** [Sycnex/Windows10Debloater#32]
Greetings.  I ran this today in it's current form and noted that Paint3D was removed even though it was whitelisted. I checked and the Version 1803 (Education)  (with build 17134.112  () lists the appx Package for Paint3D looks like it is: Microsoft.MSPaint                              Microsoft.MSPaint_4.1805.15037.0_x64__8wekyb3d8bbwe . I amended your script and then retested satisfactorily. Thanks so much for your work on this script.  You are a timesaving hero!

**Comment by gusrice** [comment]
As an add in comment it worked perfectly in version 1709.

**Comment by Sycnex** [comment]
I added Microsoft.MSPaint as a wildcard by doing *Microsoft.MSPaint* with an * appended to the end so that anything containing that name is not removed.

I am happy you like my work! It means a lot :)
