### ISSUE TITLE
not able to download using quick download link 

### ISSUE THREAD

**Issue by ksanjeev284** [Sycnex/Windows10Debloater#320]
iwr : Unable to connect to the remote server
At line:1 char:1
+ iwr -useb https://git.io/debloat|iex
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

I am getting this error

**Comment by Sycnex** [comment]
@ksanjeev284 - Can you please try again? I am having no issues with it.

**Comment by ksanjeev284** [comment]
Yeah now its working thanks
