### ISSUE TITLE
Live tiles in start menu does not work after debloating

### ISSUE THREAD

**Issue by marc-ocampo** [Sycnex/Windows10Debloater#325]
Not sure if this is really an issue but might be better if it is documented that live tiles won't work after debloating.
Or better, have an option to not include live tiles in debloating

**Comment by RavECYCLE** [comment]
I am also having this issue, while my custom tiles remain for certain programs I use there is no colour scheme (everything is grey) and I cant add new live tiles at all or modify the colour of any of my current tiles. 

I had assumed that the debloating would simply remove the windows default tiles and not mess with the functionality of the whole start menu this doesnt seem to be the case. 

Any ideas for a revert for that option??

**Comment by Sycnex** [comment]
It may be a good idea for me to put in a system restore option in the script before the code is ran. I unfortunately don’t have an idea on how to fix that in particular. Does the Revert settings resolve this in the GUI app?

**Comment by marc-ocampo** [comment]
Yes, the revert settings resolved it so I didn't have much trouble to go back.

**Comment by Sycnex** [comment]
Awesome, good to hear that. I will add a task list for myself to add System Restore to the GUI script.
