### ISSUE TITLE
How to re-enable/re-install OneDrive?

### ISSUE THREAD

**Issue by HumanGamer** [Sycnex/Windows10Debloater#327]
I removed OneDrive when I first installed Windows 10 Pro, but now I need to re-enable it. How can I do that?

**Comment by WormChickenWizard** [comment]
Run the one drive setup.
32 bit
`%SystemRoot%\System32\OneDriveSetup.exe`
64 bit
`%SystemRoot%\SysWOW64\OneDriveSetup.exe`

**Comment by HumanGamer** [comment]
Thank you, that worked. When I looked at the script it was doing a bunch of registry stuff and I wasn't sure the proper way to restore it. I thought there would be more to it. Also I'm surprised it keeps the installer on the system.

Thank you.
