### ISSUE TITLE
meaning of checkbox in the blacklist

### ISSUE THREAD

**Issue by changemenemo** [Sycnex/Windows10Debloater#336]
Hi,

Because of a bit of a lack of context, what's the meaning of the checkbox nin the list of bloatware? Is it to add it to the whitelist or to the blocklist? Because you did write blacklist on the main menu but then up the new popup you writ white and black list which confuses me a lot.
So when something is checked will it be removed or kept?

**Comment by DillonRing** [comment]
I have this exact same issue!

**Comment by changemenemo** [comment]
Please anyone to shed some lights about it ?

**Comment by xLeviathan99** [comment]
As far as i know the checked boxes will be removed

**Comment by changemenemo** [comment]
What do you mean ? Why would it be removed ?

**Comment by changemenemo** [comment]
A little sub question would be that: is it still possible to use some windows store apps after having used the script or not ?

Because I would like to use it on a tablet to unload some of the windows tasks but still being able to use Nebo to handwriting on it

**Comment by ecesar88** [comment]
I have the same question, can't tell if the apps that I check are going to be removed or not.

**Comment by WoodyPampa** [comment]
Checked mean = Remove/disable it

**Comment by Sycnex** [comment]
Thank you @WoodyPampa
