### ISSUE TITLE
"Microsoft Edge is managed by your organization" How to fix this?

### ISSUE THREAD

**Issue by yashptel** [Sycnex/Windows10Debloater#337]
Because of this issue I can't change many of the privacy related settings in the edge. Please someone tell me how to fix this.

**Comment by GitRain1281** [comment]
@yashptel 
Check this out...https://youtu.be/pn9E5ye2EAk. 
Resolving the issue seems straight forward if you are using WinPro, however, if you are on WinHome you will have to become Scuba Steve. Hopefully this will resolve the group policy issue.

**Comment by yashptel** [comment]
Ok, thanks for the help. But I already clean installed again. Closing the issue now.
