### ISSUE TITLE
Silent always prompts for 'Yes'

### ISSUE THREAD

**Issue by itsdrinkingthewater** [Sycnex/Windows10Debloater#34]
Im running ".\Windows10Debloater.ps1 -debloat" but it still asks to Yes or Revert.

What switches will allow me to run true sliently without prompt is Task Sequence?

**Comment by xsisbest** [comment]
-Debloat - SysPrep

**Comment by Sycnex** [comment]
Hi,

You should be using those parameters with the Windows10SysPrepDebloater.ps1, not the Windows10Debloater.ps1.

**Comment by Sycnex** [comment]
I am going to close this since I have not heard a response.

**Comment by itsdrinkingthewater** [comment]
Well I didnt get an answer?

**Comment by itsdrinkingthewater** [comment]
Anyway I just hard set the switches in the script, but FYI would be nice to have a working silent switch for ".\Windows10Debloater.ps1 -debloat"

**Comment by Sycnex** [comment]
The silent script with the switches that you're looking for is the
Windows10SysPrepDebloater.ps1.
