### ISSUE TITLE
Unable to Revert "Your Phone"

### ISSUE THREAD

**Issue by AviralSaxena** [Sycnex/Windows10Debloater#347]
I debloated Your Phone program and now i need it.
So, i ran the following scripts :
1. "C:\Users\[PC Name]\Desktop\Windows10Debloater-master\Windows10Debloater.ps1 -Revert" 
2. "C:\Users\[PC Name]\Desktop\Windows10Debloater-master\Windows10Debloater.ps1 Revert-Changes, Enable-Phone"
But none of them worked and the app is still showing "This app has been blocked by your system administrator"
Please help.

**Comment by Sycnex** [comment]
If the app has been blocked by your System Administrator, then you'll need to check with your System Administrator.
