### ISSUE TITLE
Some settings are managed by your organization

### ISSUE THREAD

**Issue by Rielen** [Sycnex/Windows10Debloater#35]
After using the debloater this popped up in my windows 10 updating section. Could there be a further explanation on why this may be and how to undo it?

Thank you

**Comment by Sycnex** [comment]
Hi @Rielen, what popped up?

EDIT: I understand now. When it says that settings are managed by your organization, it means that some settings are managed by GPO (Group Policy Objects) set by Group Policy Management within a domain controller. 

My script actually does change some registry keys used by GPOs.

**Comment by Sycnex** [comment]
@Rielen Any update?

**Comment by Sycnex** [comment]
I am going to close this issue. Please open a new one if you are having trouble. I believe my answer on July 10 was appropriate.

**Comment by ghost** [comment]
So.. is there a way to undo it or what?
