### ISSUE TITLE
How to avoid deleting Ubuntu WSL

### ISSUE THREAD

**Issue by WrathofBhuvan11** [Sycnex/Windows10Debloater#350]
Is there a way to not delete Ubuntu WSL ? If yes please explain how.

**Comment by wb1016** [comment]
press _customize blacklist_ on GUI, uncheck ubuntuonwindows(or something similar) and run customized script.

**Comment by Sycnex** [comment]
@wb1016 is correct.

**Comment by charlesdarkwind** [comment]
Very weird that installed wsl distros are even considered bloat. And, by the way, they're not restored by windows restore so you can kiss them goodbye if you miss the little checkbox in the blocklist.
