### ISSUE TITLE
Unpin tiles from stat menu does not work

### ISSUE THREAD

**Issue by upgradedcloud** [Sycnex/Windows10Debloater#351]
Downloaded installer using iex ((New-Object System.Net.WebClient).DownloadString('https://git.io/debloat'))
C:\Temp\Windows10Debloater exists. Skipping.
Transcript started, output file is C:\Temp\Windows10Debloater\PowerShell_transcript.DESKTOP-AG2KNCL.1esoVeSs.20210125142851.txt
Unpinning all tiles from the start menu
Unpinning all tiles from the start menu

While all the other feature work , the unpinning tiles feature hangs as above. On one instance explorer.exe was killed and had to be restarted.

Windows 10 OS Build 18363.1316

Start time: 20210125142851
Username: DESKTOP-A\work
RunAs User: DESKTOP-A\work
Configuration Name: 
Machine: DESKTOP-A(Microsoft Windows NT 10.0.18363.0)
Host Application: C:\Windows\SysWOW64\WindowsPowerShell\v1.0\powershell.exe
Process ID: 22336
PSVersion: 5.1.18362.1171
PSEdition: Desktop
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.18362.1171
BuildVersion: 10.0.18362.1171
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1

**Comment by felipecrs** [comment]
Same here.

**Comment by xaliazhar** [comment]
same here

**Comment by Sycnex** [comment]
I believe the code to unpin tiles has been outdated at this point and does not work as expected. I will work to find a fix for this.
