### ISSUE TITLE
'Windows10DebloaterGUI.ps1' is not recognized

### ISSUE THREAD

**Issue by JohnnyHalo** [Sycnex/Windows10Debloater#384]
in PowerShell ISE as Administrator, in the unzipt directorty, after executing 'Set-ExecutionPolicy Unrestricted -Force', I get the error:
-------
Windows10DebloaterGUI.ps1 : The term 'Windows10DebloaterGUI.ps1' is not recognized as the name of a cmdlet, function, script 
file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try 
again.
At line:1 char:1
+ Windows10DebloaterGUI.ps1
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Windows10DebloaterGUI.ps1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 ------
I am at a loss. renamed file to RunMe. ps1 and tried again with no joy.   /headscratch  (and thank you)

**Comment by JohnnyHalo** [comment]
Note: 
PS D:\w10db> Get-ExecutionPolicy -List

        Scope ExecutionPolicy
        ----- ---------------
MachinePolicy       Undefined
   UserPolicy       Undefined
      Process       Undefined
  CurrentUser    Unrestricted
 LocalMachine    Unrestricted
-----------------
still no joy. steep learning curve for me, reset CurUsr to undefined and am backing slowly away from the keyboard

**Comment by Sycnex** [comment]
Have you extracted the contents from the .zip file and then tried running the file?

**Comment by JohnnyHalo** [comment]
Thank you Sycnex. Yes I did.
I unzpt to D:\w10db and then opened PowerShell ISA in admin mode and ran the following . . .
=========
PS C:\Windows\system32> cd d:\w10db
PS D:\w10db> dir  (all files showed in dir)
PS D:\w10db> Windows10DebloaterGUI.ps1
Windows10DebloaterGUI.ps1 : The term 'Windows10DebloaterGUI.ps1' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ Windows10DebloaterGUI.ps1
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Windows10DebloaterGUI.ps1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
PS D:\w10db> Get-ExecutionPolicy -List
        Scope ExecutionPolicy
        ----- ---------------
MachinePolicy       Undefined
   UserPolicy       Undefined
      Process       Undefined
  CurrentUser    Unrestricted
 LocalMachine    Unrestricted
========
I also verified all permissions are granted in Windows10DebloaterGUI.ps1 file properties security tab. Thank you again. I'm missing something. I have tried more than one dwnld of the zipt file.

**Comment by Sycnex** [comment]
Hmm, have you tried just right clicking the file and running it? What about opening ISE and opening the file from there and running it?

**Comment by JohnnyHalo** [comment]
I gave done both and still encounter the " 'Windows10DebloaterGUI.ps1' not recognised " error. I have checked user permissions for the  file in the file's properties and set them to 'unrestricted' for CurentUser and Local Machine.
will try another download, unzip to a newly created directory  directory, run PowerShell ISE in Admin mode and try both running the program in PowerShell and from Explorer. Thank you for sticking with me ! as a note, I'm using the version provided by the download button, not an older or second hand copy.

**Comment by JohnnyHalo** [comment]
All I can think of at this point is a Win10 reinstall. No worries. If there is something buggy in my Windo$ setting, I'd just as soon root it out. I'm happy to close this for now and do thank you for your time and kind attention. -  John
