### ISSUE TITLE
Remove Onedrive from Windows 10

### ISSUE THREAD

**Issue by klxz79** [Sycnex/Windows10Debloater#39]
I know it's not a Windows Store app but the OneDrive that's included with Windows 10 that always prompts you for an update after logging in, and that always downloads the update in the background, and hogs a lot of CPU resources is annoying.  Can you script a way to get rid of that one too?

**Comment by Sycnex** [comment]
Does the option within the script to remove OneDrive not remove this one as well?

**Comment by klxz79** [comment]
I didn't see that was added with the newer versions.  Sorry, yes that works.  Thanks you
