### ISSUE TITLE
lost progress on gt racing 2

### ISSUE THREAD

**Issue by erikiorai** [Sycnex/Windows10Debloater#394]
hi i used tis tool and this crap eleted all my uwp apps forcently i recovered asphalt 9 proggres but gt racing 2 startedd over how to recover my proggres and please don't delete user data withaout a warrning ok

**Comment by Sycnex** [comment]
I am unsure how to recover your progress. Usually that is saved to the Microsoft cloud. I have warnings on the front of the GitHub page that this is used at your own risk. I am also not intentionally deleting any user data.
