### ISSUE TITLE
Request:  Full list of removed apps?

### ISSUE THREAD

**Issue by Krytical13** [Sycnex/Windows10Debloater#4]
Is there any way you can provide a full list of what is removed in the readme?

I see quite a few things that don't appear to be the typical "Alarm Clock" "Xbox" or other similar apps.

a lot of .net framework stuff appears to fly across the screen as it's removed

**Comment by Sycnex** [comment]
Sure, I pulled the list from old code. Also, nothing such as the .NET framework or anything of that nature is removed, since it is necessary to the OS to function. I added a -verbose option so that it says what it is acting on.

I also added -ErrorAction SilentlyContinue so that it doesn't show all of the exceptions of stuff it cannot remove, such as the .NET framework stuff, since it just fills up the screen with exceptions. This way it looks clean. Anything that the OS depends on to function is not touched. 

I am thinking of going back to blacklisting which apps I want removed instead of whitelisting, like it is now.

Here is the list of stuff removed:

             "Microsoft.3DBuilder"
            "Microsoft.Microsoft3DViewer"
            "Microsoft.Appconnector"
            "Microsoft.BingFinance"
            "Microsoft.BingNews"
            "Microsoft.BingSports"
            "Microsoft.BingWeather"
            "Microsoft.WindowsCamera"
            #"Microsoft.FreshPaint"
            "Microsoft.Getstarted"
            "Microsoft.MicrosoftOfficeHub"
            "Microsoft.MicrosoftSolitaireCollection"
            "Microsoft.MicrosoftStickyNotes"
            "Microsoft.Office.OneNote"
            "Microsoft.OneConnect"
            "Microsoft.People"
            "Microsoft.SkypeApp"
            #"Microsoft.StorePurchaseApp"
            #"Microsoft.Windows.Photos"
            "Microsoft.WindowsAlarms"
            #"Microsoft.WindowsCalculator"
            "Microsoft.WindowsMaps"
            "Microsoft.WindowsPhone"
            "Microsoft.WindowsSoundRecorder"
            #"Microsoft.WindowsStore"
            "Microsoft.XboxApp"
            "Microsoft.XboxGameOverlay"
            "Microsoft.XboxSpeechToTextOverlay"
            "Microsoft.XboxIdentityProvider"
            "Microsoft.XboxGameXCallableUI"
            "Microsoft.ZuneMusic"
            "Microsoft.ZuneVideo"
            "microsoft.windowscommunicationsapps"
            "Microsoft.Wallet"
            "Microsoft.MinecraftUWP"
            "Microsoft.NetworkSpeedTest"
            "Microsoft.PPIProjection"
            "Microsoft.MicrosoftPowerBIForWindows"
            "AdobeSystemsIncorporated.AdobePhotoshopExpress"
            "Microsoft.CommsPhone"
            "Microsoft.ConnectivityStore"
            "Microsoft.Messaging"
            "Microsoft.Office.Sway"
            "Microsoft.OneConnect"
            "Microsoft.WindowsFeedbackHub"
            "Microsoft.BingFoodAndDrink"
            "Microsoft.BingTravel"
            "Microsoft.BingHealthAndFitness"
            "Microsoft.WindowsReadingList"
            "Microsoft.MicrosoftSolitaiteCollection"
            "9E2F88E3.Twitter"
            "PandoraMediaInc.29680B314EFC2"
            "Flipboard.Flipboard"
            "ShazamEntertainmentLtd.Shazam"
            "king.com.CandyCrushSaga"
            "king.com.CandyCrushSodaSaga"
            "king.com.*"
            "ClearChannelRadioDigital.iHeartRadio"
            "4DF9E0F8.Netflix"
            "6Wunderkinder.Wunderlist"
            "Drawboard.DrawboardPDF"
            "2FE3CB00.PicsArt-PhotoStudio"
            "D52A8D61.FarmVille2CountryEscape"
            "TuneIn.TuneInRadio"
            "GAMELOFTSA.Asphalt8Airborne"
            "TheNewYorkTimes.NYTCrossword"
            "DB6EA5DB.CyberLinkMediaSuiteEssentials"
            "Facebook.Facebook"
            "flaregamesGmbH.RoyalRevolt2"
            "Playtika.CaesarsSlotsFreeCasino"
            "46928bounde.EclipseManager_2.2.4.51_neutral__a5h4egax66k6y"
            "ActiproSoftwareLLC.562882FEEB491_2.6.18.18_neutral__24pqs290vpjk0"
            "AdobeSystemsIncorporated.AdobePhotoshopExpress_1.3.2.4_x64__ynb6jyjzte8ga"
            "ActiproSoftwareLLC.562882FEEB491"

If you have any other questions or concerns please let me know.
