### ISSUE TITLE
Freshpaint

### ISSUE THREAD

**Issue by a60wattfish** [Sycnex/Windows10Debloater#4]
https://github.com/Sycnex/Windows10Debloater/blob/b7b8a1d0825b24fdcc919adf003f44ba70a1d556/Windows10Debloater.ps1#L22

Freshpaint doesn't exist in Windows 10 anymore. This might be better being replaced with MSPaint, which is Paint 3D. Proper paint is available under windows accessories and unaffected by the app store.

**Comment by Sycnex** [comment]
This is now changed. Thank you!
