### ISSUE TITLE
Trying to undo the debloater

### ISSUE THREAD

**Issue by MoonShadow28** [Sycnex/Windows10Debloater#405]
I have been trying to get my windows photos application to come back(along with a couple other photo related things). Tried everything i could think of. Downloaded old versions of the debloater to reset changes and changed the block/allow list. 
At this point i just want the rebloat everything and try again by only removing applications i do not use/ need for my pc to run. Any help would be appreciated.

**Comment by Nantris** [comment]
So did you figure this out? I assume you just followed the readme?
