### ISSUE TITLE
Windows 11 Compatibility

### ISSUE THREAD

**Issue by pegvin** [Sycnex/Windows10Debloater#413]
Hi there i tested out the GUI script on Windows 11 Insider Preview and the script works fantastic, tho i saw some issues but they were from my end.

More about the OS i tested on -
Edition:            Windows 11 Home Single Language
Update:            21H2
Installed on:     ‎7/‎1/‎2021
OS build:          22000.51
Experience:       Windows Feature Experience Pack 421.16300.0.3

**Comment by pratyush-1327** [comment]
> Hi there i tested out the GUI script on Windows 11 Insider Preview and the script works fantastic, tho i saw some issues but they were from my end.
> 
> More about the OS i tested on -
> Edition: Windows 11 Home Single Language
> Update: 21H2
> Installed on: ‎7/‎1/‎2021
> OS build: 22000.51
> Experience: Windows Feature Experience Pack 421.16300.0.3

can u tell what were the issues u faced ?

**Comment by pegvin** [comment]
> can u tell what were the issues u faced ?

Well when blocking a Bloatware the app used to lag/crash and i had some problems related to launching the GUI
