### ISSUE TITLE
Start menu not opening anymore

### ISSUE THREAD

**Issue by Aaxiruz** [Sycnex/Windows10Debloater#417]
I used the script and now I can't open start menu I click on the icon but it just loads for a second and then does not open I have tried many times but nothing happens

**Comment by ghost** [comment]
Restart your local system and this issue will be fixed.

**Comment by Aaxiruz** [comment]
> Restart your local system and this issue will be fixed.

Just restart pc? I already did it

**Comment by ghost** [comment]
https://www.windowscentral.com/windows-11-build-22000176-fix-taskbar-start-menu

**Comment by Aaxiruz** [comment]
I am using windows 10

**Comment by ghost** [comment]
> I am using windows 10

Just reinstall the whole thing.

**Comment by Aaxiruz** [comment]
> > I am using windows 10
> 
> Just reinstall the whole thing.

I had a restore point and after I restored I tried it again and still didn't work

**Comment by ghost** [comment]
Wipe that windows 10 off that storage and reinstall the os.

**Comment by tort-oise** [comment]
If no further input has been provided, or if you've found a fix, please close this issue. Or elaborate more.
