### ISSUE TITLE
Only way to run this script to to set-executionpolicy to unrestricted

### ISSUE THREAD

**Issue by klxz79** [Sycnex/Windows10Debloater#42]
remotesigned used to work, now it doesn't, only unrestricted works, did the script certificate expire?

**Comment by Sycnex** [comment]
I actually never included a script certificate. However, if you like I can do that.

**Comment by klxz79** [comment]
The previous versions of your script run under remotesigned.  The latest version however does not.  As I type this I'm running one of the older version of the script with the policy set to remotesigned.

**Comment by klxz79** [comment]
I was just able to run the latest version of your script with the execution policy set to remotesigned, on version 1803.

**Comment by Sycnex** [comment]
Interesting, I didn't change anything.
