### ISSUE TITLE
cannot revert changes and reinstall "bloatware" 

### ISSUE THREAD

**Issue by DarkShadowsX5** [Sycnex/Windows10Debloater#428]
a few useful programs that shouldn't be considered bloatware like the calculator i use almost daily got missed in the custom list and now i cant get it back after trying a restore point and Revert-Changes command.

**Comment by DarkShadowsX5** [comment]
managed to reinstall the store and get my apps back.

**Comment by haolun7788** [comment]
> managed to reinstall the store and get my apps back.

How did you do this?
