### ISSUE TITLE
outdated...

### ISSUE THREAD

**Issue by Unixware** [Sycnex/Windows10Debloater#431]
sorry guys but this def does NOT remove all of the bloatware*,  the script is outdated 

*
m$ solitaite
Xbox gamebar (yes still even it trying to remove that crap, this still exist)
Your phone

thanks!

**Comment by tort-oise** [comment]
It's in the default whitelist, I think. I'm not sure why. Edit it yourself and make a pull request, if you want to remove it so badly, but if this is just going to complain about the software, please close the issue.

**Comment by Unixware** [comment]
whatever you say..
