### ISSUE TITLE
How do I revert back?

### ISSUE THREAD

**Issue by DXPOHIHIHI** [Sycnex/Windows10Debloater#433]
I would like to revert the changes this debloater has made, the first time I run this debloater the system restore point wasnt made probably because I didn't run the program properly or as administrator. Is there any way to revert back all the changes it made? I just did a new fresh install and I don't want to do it again since it takes so long.

**Comment by Facubo** [comment]
You can try to re-bloat windows by performing a "dism" fix. It's a simple command that can be executed on elevated cmd.

**Comment by dave9123** [comment]
The best way = Reinstall Windows (Always has another bloatware)

**Comment by tort-oise** [comment]
If you found a solution (which I assume you have, or circumvented the tool) then please close this issue.
