### ISSUE TITLE
Lost access to speakers

### ISSUE THREAD

**Issue by massaynus** [Sycnex/Windows10Debloater#434]
I ran the debloater script `Windows10Debloater.ps1` and just went with defaults and removed everything
I only didn't install .NET Framework 3.5 at the end so that was my only **NO**

afterwards I edited my computers policies to disable the windows defender, literally there is a policy that just needs to be enabled for windows defender to be completely turned off for good (Thank GOD that is possible XDDD)

Problem is, after I rebooted the computer -which is an HP Notebook- it lost all access to speakers
trying to reinstall any sound driver causes a blue death screen with some sort of non handled system thread exception

I've tried running the script again to revert the Registry edits and even tried installing .NET 3.5 but no luck

it seems as if the device is not connected at all!

any ideas?

**Comment by dave9123** [comment]
Go to HP Support and download the drivers there.

**Comment by massaynus** [comment]
I've that too, when i try to install them i get a blue death screen

**Comment by dave9123** [comment]
Use mediacreationtool to reinstall windows but don't forget to back up your data to another drive.

**Comment by massaynus** [comment]
yeah i was trying to avoid doing that
dual boot problems 🤣

**Comment by tort-oise** [comment]
Well, it seems like there's not much to do here. Do you mind closing this issue?

**Comment by massaynus** [comment]
ayt sure
