### ISSUE TITLE
no silent script

### ISSUE THREAD

**Issue by smith581** [Sycnex/Windows10Debloater#44]
I am not seeing a silent version of this? Am I missing something - i use this for MDT deployments and now it prompts me.

HELLLLLP :-)

There are now 2 versions of my Windows10Debloater - There is an interactive version, and a pure silent version. The silent version now utilizes the switch parameters: -Sysprep, -Debloat, and -StopEdgePDF. The silent version can be useful for deploying MDT Images/sysprepping or any other way you deploy Windows 10. This will work to remove the bloatware during the deployment process.

The interactive version is what it implies - a Windows10Debloater script with interactive prompts. This one should not be used for deployments that require a silent script with optional parameters.

**Comment by Sycnex** [comment]
Hi, are you using this script here?

Windows10SysPrepDebloater.ps1

That one has parameters and is non-interactive, while the Windows10Debloater.ps1 is interactive.

**Comment by smith581** [comment]
Mdt during deployment

Sent from iPhone

On Sep 1, 2018, at 7:53 PM, Richard Newton <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi, are you using this script here?

Windows10SysPrepDebloater.ps1

That one has parameters and is non-interactive, while the Windows10Debloater.ps1 is interactive.

**Comment by smith581** [comment]
No using the other - currently using windows10debloatersilent.

Sent from iPhone

On Sep 1, 2018, at 7:53 PM, Richard Newton <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi, are you using this script here?

Windows10SysPrepDebloater.ps1

That one has parameters and is non-interactive, while the Windows10Debloater.ps1 is interactive.

**Comment by Sycnex** [comment]
Hi, 

You will want to use this one: Windows10SysPrepDebloater.ps1

The other script Windows10Debloater.ps1 is the one that has GUI prompts.

The way the sysprep one works is by typing (for example):

C:\Temp\Windows10SysPrepDebloater.ps1 -Debloat -StopEdgePDF 

Those 2 parameters will debloat your machine then stop Edge from taking over as the default .PDF viewer.

**Comment by smith581** [comment]
Yea the sysprep version is working well thank you

**Comment by Sycnex** [comment]
Great! Please download the latest update. I removed the blacklist and the IF statements because nothing was either A) Running or B) things were being removed that shouldn't.
