### ISSUE TITLE
literary removed everything

### ISSUE THREAD

**Issue by akavkl** [Sycnex/Windows10Debloater#446]
removed ms store, package manger etc, hence making the os unusable

**Comment by akavkl** [comment]
also removed restore point

**Comment by joeypel** [comment]
This program removes exactly what it says in it's readme. It does not remove the Microsoft Store application and this so called "package manager". It definitely does leave the OS usable. Either provide more information or please do not waste the developers time.

**Comment by akavkl** [comment]
seems related to this issue
https://github.com/Sycnex/Windows10Debloater/issues/427
As I have already reset using cloud, getting useful data won't be possible, and would be better if you remove the line for "windowsstore" debloat in debloat [file](https://github.com/Sycnex/Windows10Debloater/blame/master/Individual%20Scripts/Debloat%20Windows), even though its commented

**Comment by byronbytes** [comment]
afaik, in the Windows10DebloaterGUI version, you can set a custom whitelist / blocklist where you can set items you DON'T want to remove.

Some people want to remove the windowsstore, but that's just their personal opinion. This script is mainly for completely debloating windows 10, which means it debloats most WUP (Windows Universal Platform, correct this if i'm wrong) applications that were built in.

Or, if you want, you can fork the project and remove the line yourself, and run the script like that.

**Comment by tort-oise** [comment]
Seems fixed. Mind closing this issue?
