### ISSUE TITLE
Windows Search not working

### ISSUE THREAD

**Issue by I-AM-Arnav** [Sycnex/Windows10Debloater#448]
Titile is not soo clear.
What i wanna say is that before i just ran the debloater, when we search something like 2+2, it shows the answer but now it does not.
What is the package name for this? I'd Add it using powershell
Thanks
Arnav.

**Comment by tort-oise** [comment]
Windows Search usually breaks if you remove Cortana. Run the script again and add back Cortana. You can then instead disable Cortana in your settings.

**Comment by I-AM-Arnav** [comment]
Cortana wansnt disabled/uninstalled
Anything else?
Thank you
Kind regards
Anonymous who thanks u

**Comment by tort-oise** [comment]
I looked around in the code, and it seems you can use the
`Set-ItemProperty "HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Search" BingSearchEnabled -Value 1`
command, which should work.
If that doesn't work after a restart (remember, run in admin shell) then tell me.

**Comment by tort-oise** [comment]
I tested it myself, it 100% works (without a restart) on the latest Windows version.
Please close this issue if it works for you.
