### ISSUE TITLE
Fingerprint not working after i run script

### ISSUE THREAD

**Issue by vsoftphuong** [Sycnex/Windows10Debloater#45]
How I can solve this problem? Thank

**Comment by Sycnex** [comment]
It likely removed any software associated with the fingerprint software (biometric). You will want to reinstall the manufacturer's software to resolve this.

**Comment by vsoftphuong** [comment]
Thanks

**Comment by androidacy-user** [comment]
> It likely removed any software associated with the fingerprint software (biometric). You will want to reinstall the manufacturer's software to resolve this.

no it doesn't, it does something to completely break windows hello. biometric driver is not uninstalled.
