### ISSUE TITLE
It turns my screen yellow and mouse cursor blue.

### ISSUE THREAD

**Issue by SerchBoogie** [Sycnex/Windows10Debloater#451]
I tried to check the mouse and cursor option and it is already white and color temperature on my display options is already normal, not cold, just normal like it was before running the GUI application. 

Before running the GUI application I ran "Windows10Debloater.ps1". It takes a while before doing anything so I closed it, saw if I could run it as an admin, you can't, so I ran it again, a bunch of red text appeared but it closed itself really quick. Then I ran the GUI and selected the "remove bloatware" option and my screen got this yellow tint and my mouse cursor is now blue. 

My PC is noticeable quicker now, but I don't like this yellow tint and blue cursor. 

I'm using an old AMD A4-3300 APU, Radeon HD 6410D, 4GB ram, windows 10 64bit pro. 10.0 compilation 19042, ver. 20H2

Thanks.

**Comment by nandhugp** [comment]
Go to display settings and try turning on and off night light. I got it fixed.

**Comment by SerchBoogie** [comment]
Thanks!. It worked, well actually it was already turned on, turning it off didn't work but adjusting the slider solved the issue.

**Comment by tort-oise** [comment]
If your issue is solved, do you mind closing it?
