### ISSUE TITLE
The ampersand (&) character is not allowed. 

### ISSUE THREAD

**Issue by jasontalyor7** [Sycnex/Windows10Debloater#459]
Why am I getting this error?  It seems I cannot run from the command line and need to run as a program itself?  This reminds me of the horror of dos 5.0 where you cannot test batch files on the command line since they are different languages.  Am I right?  What's the fix?  Output:

The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double quotation marks ("&") to pass it as part of a string.
At c:\util\Windows10DebloaterGUI.ps1:488 char:114
+ ... ot;analytics.event&quot;,&quot;payload&quot;:{&quot;category&quot;:&q ...
+                                                                 ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double quotation marks ("&") to pass it as part of a string.
Not all parse errors were reported.  Correct the reported errors and try again.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : MissingFileSpecification

**Comment by tort-oise** [comment]
What are you trying to run? Looking at the output, it may be the GUI version, but there is literally 0 traces of any &'s being in the code of it. If you're using a command with & in it, you can't.

**Comment by tort-oise** [comment]
![image](https://user-images.githubusercontent.com/81963124/141660565-f68f06e8-b4cc-4e4a-ba2d-ea2572cbbb1d.png)
If anything, it could be this, but it's in a string, not a command. Make sure you've downloaded the latest.

Also, just for research, what is your aim, and what are you trying to do? A few features in this script is broken, so just tell me if something's not working properly.

**Comment by tort-oise** [comment]
If you're forgetting, you need to run this in the native versions of Windows PS (ISE works too) as administrator, NOT in cmd. You can run it from those two interfaces just fine, you don't need to launch it as a program like in DOS 5.0.

**Comment by jasontalyor7** [comment]
Upon a reboot, it ran ok.  I still have the problem that from a cmd.exe shell or a left click, it opens in notepad.  But there's a run in powershell option I used today and it run without any issues.  Perhaps it was a reboot that changed everything.

**Comment by tort-oise** [comment]
You.. can't run it from cmd.exe. Because its a PowerShell script. Now, if things are fixed, please close this issue.
