### ISSUE TITLE
A couple of issue with the latest Windows10SysPrepDebloater.ps1

### ISSUE THREAD

**Issue by Barney929** [Sycnex/Windows10Debloater#46]
Hi Richard,

Great work on the script!

I've found a couple of issues with the latest version (please correct me if I'm wrong!):

1) remove line 10 - 'Remove-AppxPackagesForSysprep -ErrorAction SilentlyContinue'  as this function is no longer in the latest version.

2) Replace all instances of 'Microsoft.Paint3D' with 'Microsoft.MSPaint'

I am having issues removing PPIProjection - 'Connect' app - do you have any ideas about this at all?

Kind regards,

Ian

**Comment by Sycnex** [comment]
Thanks for catching that! I made the changes in the latest update for both scripts.
