### ISSUE TITLE
Debloat options

### ISSUE THREAD

**Issue by Arhan2007** [Sycnex/Windows10Debloater#461]
@Sycnex 
Hi, 
What's the difference between "remove all bloatware" and "remove all bloatware with custom blocklist". Will the second option only remove the ones that are select in the blocklist 
![image](https://user-images.githubusercontent.com/86308455/143446391-8faa5ee6-70a6-4e9b-8ffd-e3ce4e5c5f1d.png)

**Comment by Xtraim** [comment]
Where do you find the « all » in « remove bloatware with custom blocklist ».
Even the picture doesn’t show the « all ».

but to answer, yes, it removes based on selected in the blocklist.

**Comment by Xtraim** [comment]
> @Sycnex
> Hi,
> What's the difference between "remove all bloatware" and "remove all bloatware with custom blocklist". Will the second option only remove the ones that are select in the blocklist
> ![image](https://user-images.githubusercontent.com/86308455/143446391-8faa5ee6-70a6-4e9b-8ffd-e3ce4e5c5f1d.png)

Where do you find the « all » in « remove bloatware with custom blocklist ».
Even the picture doesn’t show the « all ».

but to answer, yes, it removes based on selected in the blocklist.

**Comment by Xtraim** [comment]
![Uploading A36EFBFF-F435-4AA1-8260-57CE7D6BCD6E.jpeg…]()

**Comment by tort-oise** [comment]
I don't believe Sycnex will answer. The script does as advertised. You set a custom blocklist with the "customise blocklist" option. Simple as that. If you don't have more questions, close this issue.

**Comment by Arhan2007** [comment]
Thanks
