### ISSUE TITLE
It seems as though this doesnt work anymore?

### ISSUE THREAD

**Issue by eduardoson** [Sycnex/Windows10Debloater#463]
Windows 10 Professional   20H2

Does it work with?  I am getting ampersand operator not allowed errors, and '<' operator is reserved for future use.

Thanks!!

**Comment by tort-oise** [comment]
Use PowerShell, and not PowerShell ISE. Also make sure to run it as admin.

**Comment by eduardoson** [comment]
Thanks for the suggestion.  I am definitely running it as administrator in and not in ISE.  I forgot to add, however, that I am in "audit mode" trying to amke these changes.

I did try several times and exactly the same result.

Thanks your your help!

**Comment by tort-oise** [comment]
So... Is this issue fixed or not? Please close it if it's been fixed.

**Comment by eduardoson** [comment]
No...its not.  See the response?

Thank you

**Comment by tort-oise** [comment]
Well, I don't believe this script is fully built to support Audit Mode. It's meant to be run _after_ a Windows installation has been made. 
What are you using Audit Mode for?

**Comment by tort-oise** [comment]
Okay then.
