### ISSUE TITLE
[Feature Request] Disable Bing results on start menu

### ISSUE THREAD

**Issue by alanfzf** [Sycnex/Windows10Debloater#469]
It could be an awesome feature to disable bing results in windows startup menu.

**Comment by tort-oise** [comment]
Hm.. While I do agree with you, I wouldn’t necessarily see the Bing results as bloat, but I think it could be a great feature nonetheless.
For now, if you want this feature, you can modify the script to include a command that does this. I don’t know any by heart, but I’m sure you can look something up.
________________________________
From: Alan David ***@***.***>
Sent: Monday, December 13, 2021 2:22 AM
To: Sycnex/Windows10Debloater
Cc: Subscribed
Subject: [Sycnex/Windows10Debloater] [Feature Request] Disable Bing results on start menu (Issue #469)


It could be an awesome feature to disable bing results in windows startup menu.

**Comment by tort-oise** [comment]
![image](https://user-images.githubusercontent.com/81963124/147309043-800fd772-0408-4bc1-bb29-97bd6ed1590c.png)
I'm afraid this is a feature already, in the GUI version. It is a part of the "Disable Telemetry" function.

**Comment by tort-oise** [comment]
If you do not want to run the GUI version, I will paste the code here. 
`        Write-Host "Disabling Bing Search in Start Menu"
        $WebSearch = "HKLM:\SOFTWARE\Policies\Microsoft\Windows\Windows Search"
        Set-ItemProperty "HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Search" BingSearchEnabled -Value 0 
        If (!(Test-Path $WebSearch)) {
            New-Item $WebSearch
        }
        Set-ItemProperty $WebSearch DisableWebSearch -Value 1`

**Comment by tort-oise** [comment]
![image](https://user-images.githubusercontent.com/81963124/147309515-9bbb00da-3908-424d-af64-3da4d8ae2d40.png)
Upon further investigation, this feature is in the main script as well. Useless issue, please close.

**Comment by alanfzf** [comment]
Thanks!
