### ISSUE TITLE
I messed up

### ISSUE THREAD

**Issue by Sneffel** [Sycnex/Windows10Debloater#470]
It uninstalled the ASUS batter health and now I can't seem to restore it. Can anybody help me out?

**Comment by tort-oise** [comment]
While I do believe MyASUS is bloat, you can easily search up "how to install (or restore) MyASUS" on the internet (the software that provides Battery Health).

**Comment by Sneffel** [comment]
A few things
I agree, MyASUS **is** bloat, but the battery health thing isn't, it's a vital part of my laptop, I believe. 
So what did I do? I tried to download it from their website, but it was nowhere to be found. I tried to download it from the MyAsus app, but it was a stripped down version from the screenshots I could find in their manuals.
What I did was downloading the battery health app from a sketchy website (the only place providing with an exe), run it, and it worked.
My suggestion is whitelisting this particular app, listing in and being more transparent about it, as if I'd seen it was listed I'd have proceeded more cautiously.

**Comment by tort-oise** [comment]
I think the battery health is apart of MyASUS. I don't think there's a way to whitelist only the battery health without whitelisting MyASUS itself. I disagree with this proposal, as HP battery health is not whitelisted either. If you need it, I suggest you re-install it.

**Comment by TheASVigilante** [comment]
> It uninstalled the ASUS batter health and now I can't seem to restore it. Can anybody help me out?

You mean [this?](https://www.microsoft.com/store/productId/9NKCLN5X4RR9)

**Comment by tort-oise** [comment]
Okay, well, this seems fixed. Do you mind closing it?

**Comment by Sneffel** [comment]
I don't think this has been fixed. All I see is "I think it's bloat, so I won't bother adding an exception or warning the user or leaving just a tiny mention of it in the notes".
I'll close it and leave this as reminder for any future reference.

**Comment by tort-oise** [comment]
It's more of that it's an user-complaint, and more over the fact that I can't.

**Comment by Sneffel** [comment]
Also, why didn't this uninstall McAfee?

**Comment by tort-oise** [comment]
I'm assuming McAfee isn't installed through the Microsoft Store.

**Comment by Sneffel** [comment]
What do you mean? I didn't install it on purpose
And their uninstalling tool was too slow, so I aborted it

**Comment by tort-oise** [comment]
This script mainly removes App-X packages, installed through the Microsoft Store, since that is the only reliable way to uninstall things through scripts. Is this McAfee installed through the Store or through some third-party .exe or MSI installer?

**Comment by Sneffel** [comment]
I don't know about that since I have no knowledge on how to check it
What's more, it doesn't show up in the installed apps, only in the task manager

**Comment by tort-oise** [comment]
Then it's been installed by an .exe, which is far harder to remove, which a simple script cannot accomplish. That's just how it is.

**Comment by Sneffel** [comment]
Can anybody help me remove McAfee completely from my laptop?
I read all the links I could find, tried with Revo Uninstaller Pro, tried following an old guide on their website telling me to delete some registry keys but it wouldn't let me.

**Comment by tort-oise** [comment]
Step 1: Go into file explorer
Step 2: Search for "McAfee" 
Step 3: Delete every folder related to it
And do the same with registry and other stuff. If it shows up in task manager, right click, show the file location, and delete the specific file that is starting the process.

**Comment by Sneffel** [comment]
Thanks, it worked. I had to do it in recovery mode or else it would fail, even if brute forced with cmd.
