### ISSUE TITLE
Service Control Manager Error

### ISSUE THREAD

**Issue by SquirmyElk2** [Sycnex/Windows10Debloater#477]
After using this program, I am getting an error related to "Service Control Manager":
The UWPService service failed to start due to the following error: 
The system cannot find the file specified.

This causes a .ses file to be created in Appdata\Local\Temp every time I start Windows.

I was attempting to remove Edge PDF forcing and disable telemetry. (I did run the script with Administrator PowerShell)

This happened when I restarted the PC after using the program, before and when I reverted changes. It was never happening until yesterday when I used this program.

Not sure if this is intentional or not.

I'll provide the XML from Event viewer if needed.

Edit: Fixed the error using the Autoruns tool from SysinternalsSuite.

**Comment by tort-oise** [comment]
Service Control Manager is a process that is apart of the telemetry. In theory, it is a remote procedure call (or just RPC) server.

I believe there is some start-up task that keeps trying to start Service Control Manager. Try searching online on how to disable it properly, there might have been some error with the script. I also trust you ran the script as administrator. If you did not, please run it again with administrator permissions.
