### ISSUE TITLE
What does the check mark boxes mean in the "Customise Blocklist" button for the Windows10DebloaterGUI?

### ISSUE THREAD

**Issue by AndrewN20** [Sycnex/Windows10Debloater#479]
I got a question regarding what the check mark boxes when clicking on them in the "Customise Blocklist" button when running the Windows10DebloaterGUI. Does the checked boxes mean that it is the files you want to uninstall/delete? Or does the unchecked boxes represent the files you want to uninstall/delete?
![DebloaterHelp](https://user-images.githubusercontent.com/67338827/148155427-a9fae524-bbea-4126-9570-86af59f42a45.PNG)

**Comment by uhthomas** [comment]
https://github.com/Sycnex/Windows10Debloater#allowlist-and-blocklist

> There may be some confusion, but when using the Allowlist/Blocklist, the checkmark means it is on the blocklist, and that it will be removed.

**Comment by tort-oise** [comment]
Hi! Please read the README before making an issue, or search already-existing issues for similar problems. As this is not a real issue, please close it.
