### ISSUE TITLE
`Stop Edge takeover` and `Disable/Telematry tasks` block Office.com and related services

### ISSUE THREAD

**Issue by quangamedev** [Sycnex/Windows10Debloater#490]
I used the 2 mentioned features, it did remove some toll on my RAM but blocked those sites. After going back to created system restore point, I still could not access anything Office related. I also could not login to Onedrive.

I have a problem only on the network I connected to when I ran the script, my other network is not affected (tested on phone). I restarted and reset the router connected to my PC, it works for a bit but eventually blocks Office services agian.

**Comment by tort-oise** [comment]
I.. don't know if that has anything to do with the script. It shouldn't block the domain itself, only modify a few registry keys.

**Comment by quangamedev** [comment]
> I.. don't know if that has anything to do with the script. It shouldn't block the domain itself, only modify a few registry keys.

Thank you for your response. After trying to undo the procedure, Office and OneDrive worked again, sort of. Sometimes I still had to re-login into OneDrive every time my PC boots but that's considerably better than the initial problem.
