### ISSUE TITLE
Start menu tiles gone and system restore unable to fix it

### ISSUE THREAD

**Issue by massivepickle** [Sycnex/Windows10Debloater#492]
So yeah the start menu tiles part is gone and I wonder what the 'revert' button is for because it does nothing besides adding stuff that wasn't even previously there.
System restore is giving an unsuccessful error and isn't possible to deal with it like that. So, can someone help me as to how I can get the tiles section back?

**Comment by tort-oise** [comment]
What? Do you mean the "pinned to Start" programs?

**Comment by tort-oise** [comment]
Just re-pin a couple of applications with this button through the start menu.
![image](https://user-images.githubusercontent.com/81963124/153674202-50abfef5-2f1c-408c-bfb6-d3deec469e3e.png)

**Comment by proqbr** [comment]
> What? Do you mean the "pinned to Start" programs?

![image](https://user-images.githubusercontent.com/58514716/153716032-b8ee7466-37a7-420b-8de9-373593a03fb8.png)
