### ISSUE TITLE
Windows Store suddenly crapped out after weeks of working fine

### ISSUE THREAD

**Issue by Nantris** [Sycnex/Windows10Debloater#501]
Knowing Microsoft, it's very likely it's their fault - but I wonder if there's anything I should try in case it's caused by running the debloater in the past?

**Comment by GeneralZero** [comment]
I fixed mine there was an issue with my simplewall firewall. Had to manually delete all blocks and specifically enable an app on the UWP apps page.

**Comment by Nantris** [comment]
Mine was also an issue with my firewall (TinyWall.) Putting it into learning mode and opening the Microsoft Store worked fine.
