### ISSUE TITLE
script didn't do anything?

### ISSUE THREAD

**Issue by chenks** [Sycnex/Windows10Debloater#505]
am i missing something obvious?
i ran `iwr -useb https://git.io/debloat|iex` via powershell (admin rights), chose "remove all bloat", it did it thing and the powershell window appeared to do what it should do, however once i rebooted and then logged in a new user nothing was removed.

all start tiles were still there.
all the "bloat" was still in place.

i ran it on Win0 21H2 19044.1620

**Comment by Sdrtech1** [comment]
Did It remove the content from the Admin account?

**Comment by danielok1993** [comment]
Same here, the script executed but nothing was deleted.

**Comment by SlyCooperReloadCoded** [comment]
I can confirm this, script does nothing.  In my case I had already unpinned the start menu tiles and this script not only didn't remove any bloatware, it even re-pinned all the tiles.

**Comment by ghost** [comment]
For me, it did remove the pinned tiles, but didn't remove any of the bloatware using the "remove all bloatware" button.

**Comment by chenks** [comment]
Closing as seems to be a dead project
