### ISSUE TITLE
Missing Curly?

### ISSUE THREAD

**Issue by BowieFunes** [Sycnex/Windows10Debloater#51]
Hi there! I just tried the script, it's awesome, but the first time it was throwing me an error at 247/29, saying that there's a MissingEndCurlyBrace. I added the } to finish the function FixWhitelistedApps and the script worked fine afterwards.

Many thanks!

**Comment by Sycnex** [comment]
You're welcome! I'll put out an update to fix this after work today. Sorry
about the delay in response.

**Comment by smith581** [comment]
fingers crossed
________________________________

**Comment by Sycnex** [comment]
This is fixed in the latest commit.
