### ISSUE TITLE
This red lines messages in Powershell are expected?

### ISSUE THREAD

**Issue by ZeroCool22** [Sycnex/Windows10Debloater#513]
![Screenshot_4](https://user-images.githubusercontent.com/13344308/167279201-7bcfeccf-555c-4b86-b71e-9f3dbf148a11.png)

**Comment by mhafiz17** [comment]
did you try running in admin?

**Comment by ZeroCool22** [comment]
> did you try running in admin?

That was the problem.

Thx.
