### ISSUE TITLE
this is what I get when I try to run it

### ISSUE THREAD

**Issue by smith581** [Sycnex/Windows10Debloater#52]
Param : The term 'Param' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is 
correct and try again.
At line:8 char:1
+ Param (

**Comment by Sycnex** [comment]
Hi,

Is this the Windows10SysPrepDebloater.ps1 script? Are you running the script as an Administrator? Sounds like perhaps some code is missing in the script. Did you happen to modify it?

Try giving the Windows10Debloater.ps1 script a shot and see how that works out for you. I was not able to reproduce this on my machine.

Param is just an alias for Parameter and specifies which parameters can be used within the script:

E.g. param (
    [switch]$Debloat, [switch]$SysPrep, [switch]$StopEdgePDF, [Switch]$Privacy
)

**Comment by smith581** [comment]
That was from Ise

Sent from iPhone

On Oct 3, 2018, at 8:10 PM, Richard Newton <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

Is this the Windows10SysPrepDebloater.ps1 script? Are you running the script as an Administrator? Sounds like perhaps some code is missing in the script. Did you happen to modify it?

Try giving the Windows10Debloater.ps1 script a shot and see how that works out for you. I was not able to reproduce this on my machine.

Param is just an alias for Parameter and specifies which parameters can be used within the script:

E.g. param (
[switch]$Debloat, [switch]$SysPrep, [switch]$StopEdgePDF, [Switch]$Privacy
)

**Comment by Sycnex** [comment]
Did you try using the Windows10Debloater.ps1 script as an admin in ISE?

**Comment by Sycnex** [comment]
Hi, any progress, @smith581 ?

**Comment by smith581** [comment]
I just went back to my old script that works - I have seen so many corrections I can't tell what script to use - ….. you can kill this if you need to.
