### ISSUE TITLE
Deletes all personal files from desktop without warning

### ISSUE THREAD

**Issue by GermanTacos** [Sycnex/Windows10Debloater#533]
Thanks for noting that it will nuke all personal files you stupid fuck

**Comment by Faty100** [comment]
LOL

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Jacob ***@***.***>
Sent: Saturday, October 22, 2022 2:57:47 PM
To: Sycnex/Windows10Debloater ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Sycnex/Windows10Debloater] Deletes all personal files from desktop without warning (Issue #533)


Thanks for noting that it will nuke all personal files you stupid fuck

**Comment by GermanTacos** [comment]
kill yourself faggot
