### ISSUE TITLE
"Getting Ready"

### ISSUE THREAD

**Issue by smith581** [Sycnex/Windows10Debloater#54]
Myself and another colleague have been having issues with "getting Ready" getting stuck for up to 40 minutes. the one thing that we have in common is this script. there is a service that gets turned off "dmwappushservice" this is the cause of the image getting stuck. You may want to leave that service on.

**Comment by Sycnex** [comment]
Hmmm, I will add a line of code to check if it is off, and if so then it will start. Is this for the Windows10Debloater.ps1 or Windows10SysPrepDebloater.ps1?

**Comment by smith581** [comment]
Windows10SysPrepDebloater.ps1

**Comment by Sycnex** [comment]
This should now be fixed in the latest update. I added a function called CheckService that will check if the dmwappushservice is stopped and if it finds that it is stopped then it will start it.

Please let me know if that helps.
