### ISSUE TITLE
Windows explorer opens when I press the Windows key

### ISSUE THREAD

**Issue by Wackgamer** [Sycnex/Windows10Debloater#544]
Hello there,

I have used your program, deleting bloatware and bloat regs, also stopping the services of telling Microsoft and I have installed .NET there.

Do you know why is the explorer.exe opening when I press the windows key?

Hope you can give me a solution!!

**Comment by chamele0n** [comment]
A couple ideas.

1) Is your "E" button stuck down, or sticky? "Windows Key + E" opens explorer. 

2) Can you check your regirsty and make sure this key (folder) doesn't exist HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Keyboard Layout\Scancode Map
if it does, delete the whole folder for "Scancode Map" and restart the computer.  This would set the keyboard layout back to default with no remmapping of keys.

I don't see anything in the code that would remap keys.

**Comment by Wackgamer** [comment]
I could fix that problem with just only restarting the computer. But anyway, thank you for answering :)
