### ISSUE TITLE
Trouble with Read/Write permissions after running

### ISSUE THREAD

**Issue by BlutUndEisen** [Sycnex/Windows10Debloater#56]
I've run it on two patched Win 10 1803 computers in the last week and it completes the debloat but afterward I get errors ("Error 0x80070522, A Required Privilege Is Not Held By The Client"). I managed to resolve it fairly quickly by enabling the magic admin account (net user administrator) and re-enabling full control for Administrators and read/write for authenticated users (doing just one didn't seem to fix it). Wondering if this is something in the script or just an EBKAC. Tested just now on another system, same result except when I changed the permissions for the user it still did not correct the problem and I couldn't copy to the C:\ drive.

**Comment by Sycnex** [comment]
After doing some reading online, it looks like it is a permissions issue overall, with possible issues within the Registry or the user profile that is being used. I have not experienced this before. Are you using the same image for all of these machines?

Here is a good link with some solutions:

https://www.thewindowsclub.com/required-privilege-not-held-client

**Comment by smith581** [comment]
Well if you’re running the script within MDT it’s already running as system account which has admin rights so I don’t know why it would be a permissions issue necessarily

Sent from iPhone

On Oct 18, 2018, at 8:05 PM, Richard Newton <notifications@github.com<mailto:notifications@github.com>> wrote:


After doing some reading online, it looks like it is a permissions issue overall, with possible issues within the Registry or the user profile that is being used. I have not experienced this before. Are you using the same image for all of these machines?

Here is a good link with some solutions:

https://www.thewindowsclub.com/required-privilege-not-held-client<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.thewindowsclub.com%2Frequired-privilege-not-held-client&data=02%7C01%7C%7C904d5bdd49ea420d012a08d6356faf50%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636755151123478269&sdata=UPQK9Zj1N6tpwmp%2BrnTZi5HxyO7pURpRm4LQRJVyKAI%3D&reserved=0>

**Comment by Sycnex** [comment]
Ah, understood. I wasn't sure if this was when using MDT or just manually
doing it.

Have you tried it on a separate machine that wasn't imaged when using MDT?

**Comment by smith581** [comment]
I was responding to the thread it works for me 100%

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Sycnex** [comment]
Whoops, I mixed around the names. Lol.

**Comment by Sycnex** [comment]
@BlutUndEisen Any updates? If not can I close it?

**Comment by BlutUndEisen** [comment]
I haven't been able to replicate it with a fresh ISO from MS, so for now yes. If I run into the problem again I'll gather more info and make another issue. Otherwise, I'll chalk it up to something related to the image we used. Furthermore, there doesn't seem to be any lingering effects if I go back after the install and just reestablish R/W permissions for admins on the drive.
