### ISSUE TITLE
Request option to remove onedrive for business 

### ISSUE THREAD

**Issue by Benchwork** [Sycnex/Windows10Debloater#58]
after I remove office from some kiosk style systems, onedrive for business is still there. is this something that can be added as an option?

**Comment by Sycnex** [comment]
Let me look into this and find the best way to do this.

**Comment by omegis** [comment]
take a look here:
https://techjourney.net/disable-or-uninstall-onedrive-completely-in-windows-10/

**Comment by Sycnex** [comment]
I added in code to from the article @omegis linked so that OneDrive is disabled throughout Windows entirely.
