### ISSUE TITLE
Running as GPO on Startup

### ISSUE THREAD

**Issue by Faithless03** [Sycnex/Windows10Debloater#59]
Hello, 

Not sure if this is a issue or a design function, but I am trying to run the script via GPO when the computer starts up. The GPO is set at computer object and not user. It is producing a report but not removing any the default applications. 

I am using the script "Windows10Debloater.ps1" without any switches in the command. Should this work on device start up via GPO?

> **********************
Windows PowerShell transcript start
Start time: 20181106111402
Username: DOMAIN\SYSTEM
RunAs User: DOMAIN\SYSTEM
Configuration Name: 
Machine: COMPUTER-ITTES (Microsoft Windows NT 10.0.17134.0)
Host Application:  -ExecutionPolicy ByPass -File \\DOMAIN.net\SysVol\DOMAIN.net\scripts\Remove Windows 10 Default Applications\Windows10Debloater.ps1
Process ID: 780
PSVersion: 5.1.17134.228
PSEdition: Desktop
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.17134.228
BuildVersion: 10.0.17134.228
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
**********************
Transcript started, output file is C:\Windows10Debloater\PowerShell_transcript.PGB002V03-ITTES.BMc_ast2.20181106111402.txt

Thanks

**Comment by Sycnex** [comment]
Hi,

I would is the Windows10SysPrepdebloater.ps1 since that uses switches and
will run silently without any prompts or popups.

The Windows10Debloater.ps1 has popups and won't be any good for GPO.

**Comment by Faithless03** [comment]
Hi, 

So I setup the GPO to use the "Windows10SysPrepdebloater.ps1" Under the option for "Script Parameters:" I used "-SysPrep -Debloat -StopEdgePDF" 

When logging into the device, a prompt appeared asking me if I want the script to run. So I selected yes, the script has now run and remove all the apps. However I need this to work without the prompt appearing when the user logs in. Is this something in the script or I have set the GPO incorrectly? 

Thanks for this script, It is great and a much needed requirement for Windows 10 when operating a highly secured environment.

**Comment by Sycnex** [comment]
You're welcome!

You'll need to set up the script to bypass the execution policy of the
system.

Typically you'd add ExecutionPolicy -Bypass and then the name/location of
the script.

This should help:

https://blogs.technet.microsoft.com/heyscriptingguy/2010/08/14/using-group-policy-to-deploy-a-windows-powershell-logon-script/

**Comment by Faithless03** [comment]
Still having issues to get this run correctly. Has anyone been able to use it with GPO? If so, would they be willing to share the Startup Properties showing how its configured. 

As I have set mine to run at machine level on startup, ExecutionPolicy is bypassed automatically.  

After running the script manually on user 1, then logging in with user 2, all the bloatware has returned, so is it safe to assume this script is aiming at user profiles and not the device?

**Comment by Sycnex** [comment]
The script is best used when used for the current running user or before the user profile is created via MDT or another image automation process. It works great for both profiles and devices overall.

Would you be okay sending a picture with details of your settings? I normally always add the -ExecutionPolicy Bypass for best practice. Do you have this set up under user configuration or computer configuration?

**Comment by Sycnex** [comment]
@Faithless03 Have you had any luck?

**Comment by Faithless03** [comment]
Hi,

Apologies for the delay I got dragged onto another project. 

Our current deployment process is WDS, so that is why I am trying to get the script to run at system startup. The idea being. the user will experience a slow login time for the first login, but after that, it would be smooth. (From what I can tell, it needs to be run for every user that accesses the device) 

I am applying the script at User Configuration\Polices\Windows Settings\Scripts\Logon. I am selecting the script from the SysVol location and running the following Parameters -ExecutionPolicy Bypass -SysPrep -Debloat -StopEdgePDF

I am just going to deploy a new virtual machine for testing again.

**Comment by Faithless03** [comment]
Another question I have about the Script. Does it work with Windows 10 Pro? I ask, as there a number of features in Group Policy that only work with Windows 10 Enterprise. Ideally I would like to only deploy Pro, but will use Enterprise if I have no choice. 

Thanks

**Comment by fredenocs** [comment]
It'll work in PRO, yes.  This is something shouldn't be put into a GPO.

**Comment by Faithless03** [comment]
> It'll work in PRO, yes. This is something shouldn't be put into a GPO.

So how do you run it?

**Comment by fredenocs** [comment]
I do these on new deployment systems.  Whatever is in the wild, I leave alone.  So I deploy mine through my imaging process of using Microsoft MDT.  If you have a manager or someone complain about the programs on it, run it manually.

**Comment by Faithless03** [comment]
> I do these on new deployment systems. Whatever is in the wild, I leave alone. So I deploy mine through my imaging process of using Microsoft MDT. If you have a manager or someone complain about the programs on it, run it manually.

Running it manually is not an option, I have over 500 end users we need to upgrade to Windows 10 in a secure environment. Running the script on a newly prepared system does not do the job, as other users who login to the system still have access to the bloatware. That's why I need to run this script automatically every time a user access a new device.

**Comment by fredenocs** [comment]
Pardon me on the double-post, but this applies here to and I want to ensure information is relayed.


I have to comment on this, as I thought it wasn't working properly either.

I've imaged 100 machines in the last week or so.  Using MDT and sysprep version runs part of the process.  Creates a default administrator account, fine-whatever.  Tiles remain as if the apps are still present.

In my testing of my deployments, I've noticed the tiles are gone and cleaned when a new user is created, no matter how many users I create.  Administrator account remains with the tiles.

If you want those tiles gone, then create a custom start menu and taskbar to load when a user logs in.

When you run his program on the current user, it doesn't clean-up as good as if a new user logs in.

**Comment by Faithless03** [comment]
Hi,

Just to provide an update into my testing. I deployed a new Windows 10 Pro device. But before joining the domain I ran the script manually using the GUI. (It worked perfectly fine) I then joined the device to the domain, when accessing the device using a normal user account, the bloatware is removed and does not reappear, so its seems to be, if you run the script before joining the device to a domain, it will remove it for all users and every user in the future. (Hence why it works best with MDT, as the script is being run before joining a domain)

The only other question I really have. Can the script be used to uninstalled\remove the store completely? Disabling the store VIA GPO is not an option for Windows 10 Pro. (It is for Windows 10 Enterprise)  So if its possible to completely remove it, then it would solve all my problems. (Once I setup MDT)

Thanks for all the input.

**Comment by fredenocs** [comment]
You're asking for trouble, if you want the store removed completely.  There was been enough proof and information out there about this.

My script in MDT runs when the PC is on the domain already.  It's one of the final "Custom Tasks" is does when completing.  Along with customizing my start menu and taskbar.

**Comment by Zimmo** [comment]
>           You're asking for trouble, if you want the store removed completely.  There was been enough proof and information out there about this.
> My script in MDT runs when the PC is on the domain already.  It's one of the final "Custom Tasks" is does when completing.  Along with customizing my start menu and taskbar.

Hi fredenocs,
Any chance you could share a zip with the scripts you use in MDT and how they are executed from MDT(Screenshot of the task sequence in Deployment Workbench). Now I am using a set of custom scripts - and I am not too happy with them. I get Warnings and can’t get everything to Work.
 I am interested in all you are willing to share.  Start menu fix, bloatware removal, IE settings, Edge setting etc.
Note: I have not had the time to implement/test Windows10Deploater in MDT so it would be an awesome help to replicate all your adaptations/settings, so I don’t have to start testing from scratch.
Thanks.

**Comment by fredenocs** [comment]
> > ```
> >       You're asking for trouble, if you want the store removed completely.  There was been enough proof and information out there about this.
> > ```
> > My script in MDT runs when the PC is on the domain already.  It's one of the final "Custom Tasks" is does when completing.  Along with customizing my start menu and taskbar.
> 
> Hi fredenocs,
> Any chance you could share a zip with the scripts you use in MDT and how they are executed from MDT(Screenshot of the task sequence in Deployment Workbench). Now I am using a set of custom scripts - and I am not too happy with them. I get Warnings and can’t get everything to Work.
> I am interested in all you are willing to share. Start menu fix, bloatware removal, IE settings, Edge setting etc.
> Note: I have not had the time to implement/test Windows10Deploater in MDT so it would be an awesome help to replicate all your adaptations/settings, so I don’t have to start testing from scratch.
> Thanks.

Sure, but not sure we can private message here?  I don't want flood the comment section

**Comment by Zimmo** [comment]
@fredenocs please send a quick mail and i will reply from my real e-mail :) 
temporary mail: temp-akk-mail@mailinator.com 

Thank you. :)

**Comment by Sycnex** [comment]
@Faithless03 you can certainly remove the Windows Store entirely, and the scripts have the ability to do that. You will just need to go through and remove the whitelisted Microsoft.WindowsStore since right now the scripts don't remove the store.

That can be found in the DebloatAll and DebloatBlacklist functions.

**Comment by Sycnex** [comment]
Closing since there appears to no longer be an active discussion.
