### ISSUE TITLE
Silent Debloater not very "Silent"

### ISSUE THREAD

**Issue by Blu3ish** [Sycnex/Windows10Debloater#6]
When using this as a deployment using MDT at a image of Windows 10 1709 it spits out 120+ errors at the end of every deployment. Ofcourse the script continue's on error but would you know a solution for this?
Thanks in advance

**Comment by Sycnex** [comment]
Hi Blueish,

Can you provide me a screenshot by any chance?

**Comment by Blu3ish** [comment]
Ofcourse! let me copy the new script instead of the old one and i will show you the result in the deployment.

Thanks for the fast reaction!

**Comment by Blu3ish** [comment]
Error i'm getting every deployment:

![knipsel](https://user-images.githubusercontent.com/36703662/36494562-a854d73e-1732-11e8-85ab-6d7f777287ed.PNG)

[Windows10SilentDebloater.log](https://github.com/Sycnex/Windows10Debloater/files/1745004/Windows10SilentDebloater.log)

Kind regards

Rowan Janse

**Comment by Sycnex** [comment]
Hi Blu3ish,

The errors you're seeing are actually normal, but it is when the script tries to remove anything OS necessary and it throws an error stating that it can't. The script itself has a parameter, -ErrorAction SilentlyContinue, so ignore any errors that appear and to suppress them silently and continue on. As far as your MDT logs, I am not sure as to how to suppress the details since I do not use MDT.

The script is working normally, right?

**Comment by Sycnex** [comment]
Hi Blu3ish,

I added a parameter to the end of line 16l -ErrorAction SilentlyContinue in order to suppress those messages in your MDT logs. I also fixed line 227. Please let me know if it worked for you.

**Comment by Blu3ish** [comment]
Dear Sycnex

I've lost almost all errors. But not all I really apricate the change you made. after looking at the errors I’ve noticed not all versions of Windows 10 have the same scheduled tasks so I’ve added -ErrorAction SilentlyContinue on every attempt to remove a task so it will not give issues in the future neither. Please take a look at this below.

![knipsel](https://user-images.githubusercontent.com/36703662/36535517-352e4216-17ca-11e8-89b2-0eb91ba4b887.PNG)

On line 159:
`    #Disables scheduled tasks that are considered unnecessary 
    Write-Output "Disabling scheduled tasks"
    Get-ScheduledTask -TaskName XblGameSaveTaskLogon -ErrorAction SilentlyContinue | Disable-ScheduledTask
    Get-ScheduledTask -TaskName XblGameSaveTask -ErrorAction SilentlyContinue | Disable-ScheduledTask
    Get-ScheduledTask -TaskName Consolidator -ErrorAction SilentlyContinue | Disable-ScheduledTask
    Get-ScheduledTask -TaskName UsbCeip -ErrorAction SilentlyContinue | Disable-ScheduledTask
    Get-ScheduledTask -TaskName DmClient -ErrorAction SilentlyContinue | Disable-ScheduledTask
    Get-ScheduledTask -TaskName DmClientOnScenarioDownload -ErrorAction SilentlyContinue | Disable-ScheduledTask`

Now since MDT deployment seems to cry about every little error it has Function Stop-EdgePDF has some errors in it too, my PowerShell skills goes until here since I’m unable to say why it gives an object not found at line 176 and an invalid argument at line 181. Shouldn’t it be the same error?

Now  for the object not found error could be removed by adding -ErrorAction SilentlyContinue in my eyes but I am unable to say if the script functions properly after seeing the errors at line 181,186,191,201 at the PowerShell script.

thanks in advance


( [Windows10SilentDebloater2.log](https://github.com/Sycnex/Windows10Debloater/files/1747703/Windows10SilentDebloater2.log) )

**Comment by Sycnex** [comment]
Hi Blu3ish,

It looks to me as though that it is just throwing an exception because it does not see those scheduled tasks and since it doesn't see them it cannot remove them, which isn't an issue. Is it stopping MDT from running properly?

Perhaps I can move the position of the common parameter -ErrorAction SilentlyContinue.

**Comment by Sycnex** [comment]
I updated both scripts. Can you please give it another shot?

**Comment by Blu3ish** [comment]
Solved
