### ISSUE TITLE
Disable default apps on new profiles

### ISSUE THREAD

**Issue by a60wattfish** [Sycnex/Windows10Debloater#6]
I know you've seen this on reddit, but can you add the following to the Start-Debloat function? It stops default apps (Candy Crush and Minecraft) from being installed on new accounts on a computer.

```
reg load HKU\Default_User C:\Users\Default\NTUSER.DAT
Set-ItemProperty -Path Registry::HKU\Default_User\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager -Name SystemPaneSuggestionsEnabled -Value 0
Set-ItemProperty -Path Registry::HKU\Default_User\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager -Name PreInstalledAppsEnabled -Value 0
Set-ItemProperty -Path Registry::HKU\Default_User\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager -Name OemPreInstalledAppsEnabled -Value 0
reg unload HKU\Default_User
```

**Comment by a60wattfish** [comment]
After doing some testing, I believe those registry changes will also need making to HKCU at the same time, otherwise the profile you are currently using can end up receiving the files the first time it goes on the internet.

**Comment by Sycnex** [comment]
Yes, absolutely. I believe I have SystemPaneSuggestionsEnabled -Value 0 for HKCU currently, but I don't have the others for HKCU.

I'll add those in for HKU as well. 

Thanks for the additional code/help!

**Comment by Sycnex** [comment]
I added the code in with both the Windows10Debloater and the Windows10DebloaterSilent scripts.

I also credited you in the comment. Thank you!
