### ISSUE TITLE
Start menu configurations not saving on restart

### ISSUE THREAD

**Issue by crediblebytes** [Sycnex/Windows10Debloater#61]
Excellent script by the way and thanks for sharing. I did run into an issue with my configurations in the start menu not saving on a restart right after running the script. However the following steps I found on [stack exchange](https://superuser.com/questions/1242512/windows-10-start-menu-not-saving-changes) fixed the problem. Maybe we can integrate these steps into the script?
1. Open Regedit
2. Open Running Processes and end Explorer.exe (don't restart it yet), 
3. Delete the key with Regedit
HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\CloudStore
4. Start Explorer.exe again
5. Restart machine

**Comment by Sycnex** [comment]
I can certainly add this in. I will do it this weekend.

**Comment by Sycnex** [comment]
This has been completed.
