### ISSUE TITLE
muiltiple broken things

### ISSUE THREAD

**Issue by audenga** [Sycnex/Windows10Debloater#62]
cant change default apps
network status says no internet connection
have to reset mouse settings after restart
programs installed by me dont show up where they should

**Comment by Sycnex** [comment]
That sounds like a bad Windows install. I haven't experienced this myself nor has anyone else.

What version of Windows 10? And did you do this with a new profile or an existing profile? 

The fact that your machine is stating that there is no internet connection means that your network drivers are corrupt/missing and need to be reinstalled.

**Comment by audenga** [comment]
was done on a fresh and non fresh activated install - win 10 pro 1809, and i was still able to connect to internet just nothing on the microsoft side of things, store, games or edge (tested)

**Comment by fredenocs** [comment]
1809 has enough bugs no-one should be deploying it in any environment.

I blame 1809 not his program.

**Comment by Sycnex** [comment]
My script does not currently remove the Windows Store unless you uncomment out the selection, and remove it from the whitelist in both of the DebloatAll and DebloatBlacklist functions @audenga. If you use the revert changes function it should reinstall the Windows Store if you had it removed.
