### ISSUE TITLE
Consider whitelisting the Camera app

### ISSUE THREAD

**Issue by RJohnsonPGH** [Sycnex/Windows10Debloater#65]
The built in Camera app is pretty "unspammy" as far as the built in apps go. It's a pretty straightforward way to take photos/videos and change some camera settings without having to resort to third party tools.

This is really handy if you have a 2 in 1 or laptop that has an integrated camera.

**Comment by RJohnsonPGH** [comment]
Oh, the package name is `Microsoft.WindowsCamera`

**Comment by Sycnex** [comment]
Done!
