### ISSUE TITLE
kernel inpage error on New computer

### ISSUE THREAD

**Issue by limitbreakd** [Sycnex/Windows10Debloater#67]
Went ahead and ran the script on my new computer I had just received the other week. Not sure why, but I've gotten 2 different and completely random kernal inpage errors. Computer freezes, blue screen pops up, then has trouble rebooting. 

I'm was wondering if anyone else was having a similar issue?

**Comment by Sycnex** [comment]
Hi,

This is either a Windows OS corruption or related to your RAM or HDD.

The error refers to a missing or corrupt page of kernel data in a Windows
page file. This can be caused by file, memory, or disk corruption as the
term "inpage" is really exclusively hard disk or RAM related.

**Comment by limitbreakd** [comment]
Okay thanks so much for the help, I thought I might've deleted an essential file after running the script. Very much appreciate your help sir and great job with everything!!

**Comment by limitbreakd** [comment]
closing

**Comment by Sycnex** [comment]
No problem!

Just to add - my script doesn't delete any essential Windows files and
everything it does is able to be reversed. I don't ever want to make it so
that people have corrupted Windows installations because of it.
