### ISSUE TITLE
Unopened "}" character at line 227

### ISSUE THREAD

**Issue by Blu3ish** [Sycnex/Windows10Debloater#7]
There is a unexpected "}"character at line 227 of the script. I'd surgest removing the "}" at the end of line 226.

Kind regards 

Rowan Janse

**Comment by Sycnex** [comment]
Oh, I didn't catch that earlier, my apologies. I'll update it shortly here
in an hour or two.

I appreciate it!

**Comment by Blu3ish** [comment]
Solved by the creator. And thanks for doing so ;)
