### ISSUE TITLE
Disabling the WAP Push Service breaks sysprep

### ISSUE THREAD

**Issue by dcolpitts** [Sycnex/Windows10Debloater#72]
It appears that when the WAP Push Service is set to disabled, sysprep has issues including long, long hangs when generalizing is occurring and pauses both prior to reboot and during the getting ready before OOBE.

During the building and configuration of a machine, as part of the telemetry clean up when Windows10Debloater.ps1 runs, the WAP Push Service (dmwappushservice) service gets stopped and the service is set as disabled.  Then just prior to running sysprep when Windows10SysPrepDebloater.ps1 is run, it checks if the service (dmwappushservice) is stopped and tries to start it.  Unfortunately, Windows10SysPrepDebloater.ps1 does not check if the service has been disabled or not though.  Thus the dmwappushservice service doesn't start, and sysprep hangs.

I confirmed this by building a new W10Ex64 1809 VM.  I shutdown and took a snapshot after Windows was installed, then ran sysprep with a basic sysprep.xml.  Sysprep completed in 2 minutes.  I reverted the snapshot, ran Windows10SysPrepDebloater, then sysprep, and sysprep completed in 2 minutes again.  I reverted the snapshot, ran Windows10Debloater.ps1 (answering yes or ok to everything), rebooted, ran Windows10SysPrepDebloater, then sysprep.  Sysprep has been running for 15 minutes so (compared with 2 minutes previously).

dcc

**Comment by Sycnex** [comment]
I added a function in the Windows10SysprepDebloater to check if the service is disabled, and if so it sets the startup type to Automatic and then starts the service if it isn't running.
