### ISSUE TITLE
Run as Admin

### ISSUE THREAD

**Issue by Foebik** [Sycnex/Windows10Debloater#73]
I added this to the top of the **Windows10DebloaterGUI**  script to make sure it runs as admin.

Just thought it might be a nice add here.

`if (!([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole] "Administrator")) { Start-Process powershell.exe "-NoProfile -ExecutionPolicy Bypass -File `"$PSCommandPath`"" -Verb RunAs; exit }`

**Comment by Sycnex** [comment]
Done! Sorry for the delayed response. Better late than never!
