### ISSUE TITLE
 Protect-Privacy needs to add reg dword

### ISSUE THREAD

**Issue by simplyfloid** [Sycnex/Windows10Debloater#76]
On new windows installs, the people key exists but the dword PeopleBand does not. Therefore the error checking in this portion of the script erroneously bypasses disabling of the people icon:

#Disables People icon on Taskbar
    Write-Output "Disabling People icon on Taskbar"
    $People = 'HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced\People'    
    If (!(Test-Path $People)) {
        mkdir $People -ErrorAction SilentlyContinue
        New-ItemProperty $People -Name PeopleBand -Value 0 -Verbose
    }

**Comment by Sycnex** [comment]
This has been resolved :D
