### ISSUE TITLE
More bloat

### ISSUE THREAD

**Issue by gcormier** [Sycnex/Windows10Debloater#77]
Ran the GUI script, these were still around:

office lens
sway
microsoft todo list
microsoft whiteboard
network speed test
microsoft news

**Comment by Sycnex** [comment]
Can you let me know if those resolved your issue?

**Comment by gcormier** [comment]
I manually removed the packages, so can't test this one out until my next reinstall :)

**Comment by Thibaud49** [comment]
It works for me.
But there are still crap in the menu
![debloat2](https://user-images.githubusercontent.com/47252841/52135830-003c5c00-2647-11e9-8748-978ef7bac39c.png)
In addition I have a failure on the execution of powershell
![debloat](https://user-images.githubusercontent.com/47252841/52135875-1e09c100-2647-11e9-9f6a-351ba1143ff4.png)
And it seems that Cortana still works

**Comment by Sycnex** [comment]
Those are leftover tiles in the start menu, since I don't know a way to remove tiles from the start menu.

The error is just stating that there is a scheduled task that it was unable to find.

Have you given your machine a restart and checked to see if Cortana is now disabled?

**Comment by Sycnex** [comment]
Can you all run the latest updated script and let me know if it works for you?

**Comment by Sycnex** [comment]
I am going to close this for the time being. Feel free to reopen it.
