### ISSUE TITLE
some left over bloat

### ISSUE THREAD

**Issue by Wtcheesecakes** [Sycnex/Windows10Debloater#78]
bloat leftover:
Paint 3D
Sticky notes
and video editor

**Comment by smoonlee** [comment]
Is this on the Administrator Profile or New User?

**Comment by Wtcheesecakes** [comment]
admin

**Comment by Sycnex** [comment]
I have the Paint3D and Sticky Notes whitelisted by request so that they aren't removed automatically.

You can remove them from the whitelist in the scripts, by removing the Microsoft.Paint3D and Microsoft.MicrosoftStickyNotes

**Comment by ejohb** [comment]
I'm also seeing "Dolby Access" left over.

**Comment by Sycnex** [comment]
Interesting, I had it on mine as well and removed it using the standard:

 get-appxpackage -name "*Dolby*" | Remove-Appxpackage

Let me look into it.

**Comment by smoonlee** [comment]
It wont clean on an existing profile, if you create a new user account then you will see the changes.

**Comment by Sycnex** [comment]
Can you all run the latest updated version of the script and let me know if it works for you with unpinning the start menu tiles?

**Comment by Sycnex** [comment]
@Wtcheesecakes  and @EdwardJB  - Have you had a chance to try out the latest updates?

**Comment by ejohb** [comment]
Hi @Sycnex . Not been in a position to, but will likely set up another machine this weekend, so will have a look then.

**Comment by Sycnex** [comment]
@EdwardJB - Have you had a chance just yet?

**Comment by ejohb** [comment]
> @EdwardJB - Have you had a chance just yet?

Yes, I set up a VM yesterday. The Dolby thing is gone! All I see now are:

- Netflix
- Photoshop Elements
- March of Empires

**Comment by Gray-0men** [comment]
Was the VM disconnected from the internet? if windows updates were running in the background then it'll cause some apps to not get deleted

**Comment by ejohb** [comment]
Yeah it would have been online.

**Comment by Sycnex** [comment]
@EdwardJB - I am following up on old issues. Is this still an issue?

**Comment by ejohb** [comment]
Cannot say. Not run it in years. Feel free to close!
