### ISSUE TITLE
New Issue -- Issue 7 not resolved - WindowsStore

### ISSUE THREAD

**Issue by dhoffman98** [Sycnex/Windows10Debloater#8]
I'm pretty new to this myself, but I'm finding some things that just aren't working the way they are written.

When searching for AppxProvisionedPackages, there is no attribute called "name".
There is "DisplayName" and "PackageName", but not just "Name".
So lines 22 and 23 will fail to exclude "Microsoft.WindowsStore" or "Microsoft.Photos", causing them to still be deleted.

Suggest changing them like lines 20 and 21:

        Where-Object {$_.packagename -notlike "*Microsoft.WindowsStore*"} |
        Where-Object {$_.packagename -notlike "*Microsoft.Windows.Photos*"} |

**Comment by Sycnex** [comment]
This is now fixed in the latest commit. Thank you!
