### ISSUE TITLE
Bug: Param heading is wrong

### ISSUE THREAD

**Issue by Skatterbrainz** [Sycnex/Windows10Debloater#8]
The Windows10Debloater.ps1 script appears to be missing a final closing "}" on the last function.

**Comment by Sycnex** [comment]
Hi Skatterbrainz,

I cannot seem to reproduce this regardless of what I run. Can you please provide a screenshot if it is continuing to still happen?

**Comment by Sycnex** [comment]
Any update on this? Otherwise if it works can I close this issue?

**Comment by Skatterbrainz** [comment]
The issue is with having three param() blocks, it throws an error.  It should be one param() block with the [switch] params nested.

```
param([switch]$Debloat)

param([switch]$SysPrep)

param([switch]$StopEdgePDF)

```
should be...
```
param (

  [switch]$Debloat,

  [switch]$SysPrep,

  [switch]$StopEdgePDF

)
```
once I change that, everything appears to work fine.

**Comment by Skatterbrainz** [comment]
Any update on this?

**Comment by Sycnex** [comment]
Hi,

I haven't gotten a chance due to some personal life things going on. I will
update it today if I get the chance.

**Comment by Sycnex** [comment]
This has been fixed as specified.
