### ISSUE TITLE
Debloater Hangs

### ISSUE THREAD

**Issue by sjones5922** [Sycnex/Windows10Debloater#80]
Having a bit of trouble with Debloater hanging.  Running the GUI version.  First time around it got to around 102 items and then hung.  Finally aborted it.  Second time around it got to 84 and then hung.
![Uploading image.png…]()  Attempting to upload screenshot...if it fails, I will upload a different way.

**Comment by sjones5922** [comment]
![screenshot](https://user-images.githubusercontent.com/47297980/52177921-ff661000-2795-11e9-9075-194294b76b18.png)
Here is screenshot.

**Comment by sjones5922** [comment]
I might have answered my own question.  I was logged into a domain as administrator.  I logged out and logged in as local machine administrator.
Had run run an elevated Command Prompt.  
Change directory to where you have the Debloater ps1 file located. (In my case the GUI file).
Paste in the following: 
powershell -ExecutionPolicy ByPass -File Windows10DebloaterGUI.ps1
and hit enter.  
It appeared to work.
Thanks

**Comment by Sycnex** [comment]
Did it have any CPU activity while it was running? Just curious.

**Comment by fisherd80** [comment]
Having the same issue, its stops at the same point even with including the above solution.  Any advise would be welcome.

![image](https://user-images.githubusercontent.com/31191953/52636488-a6e4f000-2ec4-11e9-94ed-5a64b20e55da.png)

**Comment by iantype** [comment]
@fisherd80 I just ran the non-GUI version fine on 17134.590. If you want to get going with the debloating still I'd recommend opening the PowerShell ISE as admin and copying the non-GUI script into the Script Pane (you may need to click on View first and then enable it first to see it) and seeing how that goes (making sure to catch any prompts that may come up). 

This way if it hangs, you could add some print statements and breakpoints into the ISE to help you debug it. 

The raw PS script to save you a few clicks: https://raw.githubusercontent.com/Sycnex/Windows10Debloater/master/Windows10Debloater.ps1

**Comment by Sycnex** [comment]
@fisherd80 - I am unfortunately unable to replicate the issue. How long do you let it sit for before you close it out? It may be trying to uninstall something that it is unable to, or perhaps there is something else going on behind the scenes that is not written out.

**Comment by Sycnex** [comment]
I did some testing over the past week and I have still been unable to replicate this issue. Has anyone else been able to find the issue when you experienced it? Any debug information?

**Comment by einsteinx2** [comment]
@Sycnex I actually just had this happen to me. I have two Windows 10 Pro machines. First ran the GUI script with no issues on the first try, following the instructions in the readme. Second machine hung the first time exactly as the original poster and with no CPU usage at all, so basically completely stuck waiting for something, who knows. I killed it and re-ran it and it completed without issue. Everything that was removed on the first machine seems to have been removed on the second.

Not sure why it hung, but running it again worked for me, so maybe that can help others.

Sorry I don't have any debug info (I'm not much of a Windows user and am not familiar with PowerShell), but here's a screenshot of the first run when it hang:
![debloater hanging](https://user-images.githubusercontent.com/350423/53533850-6d1e0700-3aca-11e9-9891-164a043254a0.jpg)

**Comment by sjones5922** [comment]
Sorry for the delay in responding back.  I ran the GUI one again and it hangs around item 72.  I will load up another machine this weekend and try running it twice and see what happens.

**Comment by Gray-0men** [comment]
I fixed a number of error's and removed a lot of the failed removal attempts on apps that are flagged as NonRemovable (the green background and yellow text floating above the PS window, the apps that say initializing then hang at 0)

If you can check out my fork for the GUI and the code I changed it runs smoothly without any background errors now

 https://github.com/Gray-0men/Windows10Debloater

PS: trying to get my fork Merged over, check the comments on my commits you'll see the fixes

**Comment by Gray-0men** [comment]
I run this script or the GUI almost a dozen times a day since I remote into new Win10 installs all the time, I've been fine tuning this Debloater script after I mixed my own project with this one a little less than a year ago.

**Comment by Notaduck** [comment]
I'm seeing the same behaviour here,  it hangs at "99 activitets not show...." the windwos isn't responding and there is zero load on the cpu and it uses ~58 MB ram.

And this is done on a fresh install of Windows 10 pro

**Comment by Sycnex** [comment]
Once @Gray-0men fixes the stuff I asked for in the pull request then I will happily merge it and then this problem will be resolved :D

**Comment by Sycnex** [comment]
@notaduck Have you had a chance to run the latest Windows10Debloater.ps1?

**Comment by Notaduck** [comment]
@Sycnex I jus tried to run it again and it doesn't seems to be hanging/freezing any more.
Thanks

**Comment by mattreecebentley** [comment]
Same issue here, but what I found was that it hangs for a really long time doing nothing, then starts up again.

Then spits out "Path :
Online : True"
Over and over.

And various commands/command failures.
But it gets there.

It may be a resource conflict when windows update is installing stuff in the background.

**Comment by Sycnex** [comment]
This should be resolved in the latest updates from sometime in the last year thanks to others who were gracious enough to spend some time resolving the issue. Please open a new issue if this happens again.
