### ISSUE TITLE
Windows App Store doesn't work

### ISSUE THREAD

**Issue by yfactor8** [Sycnex/Windows10Debloater#81]
Any idea why?

It keeps giving me the "Try again later. Something happened on our end" error.

**Comment by Sycnex** [comment]
My script(s) remove dependencies most likely that the microsoft store needs. You can try running the Revert-Changes function in the Windows10Debloater.ps1 script which should fix it.

**Comment by yfactor8** [comment]
Thanks man. I appreciate the super fast response. I'll give it a try

**Comment by Sycnex** [comment]
@yfactor8  - Have you had any success with the Microsoft Store working?

**Comment by yfactor8** [comment]
Unfortunately I couldnt get it working

**Comment by Sycnex** [comment]
My apologies. Unfortunately running my scripts can make it so that the store no longer works. Interestingly, I do not have the same issue as you are having and it seems to be random with who it affects.

I am not surprised it no longer works though, due to it potentially removing some dependencies.

**Comment by yfactor8** [comment]
No worries. Appreciate the work you do regardless
