### ISSUE TITLE
No success at all.

### ISSUE THREAD

**Issue by DrTeeth707** [Sycnex/Windows10Debloater#88]
I have enabled script running on my Win 10 x64 system with the bypass function. Right-clicking and then clicking "run with PowerShell" just opens pwershell and it closes a second later.  
I also get the errors below if trying to use the PS ISE version. Please help. Thanks
![2019-02-16_17h28_23](https://user-images.githubusercontent.com/39297836/52902978-44ffef80-3210-11e9-9623-5efaeffcd8fd.png)

**Comment by Sycnex** [comment]
You need to run the script doing the following, in your case:

.\Windows10DebloaterGUI.ps1

If you don't use the .\ beforehand then it thinks you're trying to run a cmdlet.

**Comment by DrTeeth707** [comment]
Re: [Sycnex/Windows10Debloater] No success at all. (#88)



Hi Richard,

Thanks to getting back to me.

I ran the command as you suggested, and got the following:-
PS D:\> .\Windows10DebloaterGUI.ps1
At D:\Windows10DebloaterGUI.ps1:388 char:154
+ ... ex-auto js-user-status-form" action="/users/status?compact=1&amp;link ...
+                                                                 ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double
quotation marks ("&") to pass it as part of a string.
At D:\Windows10DebloaterGUI.ps1:388 char:174
+ ... us-form" action="/users/status?compact=1&amp;link_mentions=0&amp;trun ...
+                                                                 ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double
quotation marks ("&") to pass it as part of a string.
At D:\Windows10DebloaterGUI.ps1:388 char:268
+ ... TF-8" method="post"><input name="utf8" type="hidden" value="&#x2713;" ...
+                                                                 ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double
quotation marks ("&") to pass it as part of a string.
At D:\Windows10DebloaterGUI.ps1:404 char:63
+                   <span class="js-user-status-no-emoji-icon" >
+                                                               ~
Missing file specification after redirection operator.
At D:\Windows10DebloaterGUI.ps1:417 char:18
+               80 remaining
+                  ~~~~~~~~~
Unexpected token 'remaining' in expression or statement.
At D:\Windows10DebloaterGUI.ps1:504 char:183
+ ... TF-8" method="post"><input name="utf8" type="hidden" value="&#x2713;" ...
+                                                                 ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double
quotation marks ("&") to pass it as part of a string.
At D:\Windows10DebloaterGUI.ps1:509 char:14
+ </form>      </details-menu>
+              ~
The '<' operator is reserved for future use.
At D:\Windows10DebloaterGUI.ps1:555 char:242
+ ... TF-8" method="post"><input name="utf8" type="hidden" value="&#x2713;" ...
+                                                                 ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double
quotation marks ("&") to pass it as part of a string.
At D:\Windows10DebloaterGUI.ps1:573 char:93
+ ... escription">Be notified only when participating or @mentioned.</span>
+                                                                   ~
Missing property name after reference operator.
At D:\Windows10DebloaterGUI.ps1:573 char:93
+ ... escription">Be notified only when participating or @mentioned.</span>
+                                                                   ~
The '<' operator is reserved for future use.
Not all parse errors were reported.  Correct the reported errors and try again.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : AmpersandNotAllowed

Do you have any further suggestions? I am running the script from a drive other than C:.

Cheers

Guy

Sunday, February 17, 2019, 2:55:29 AM, you wrote:





You need to run the script doing the following, in your case:
.\Windows10DebloaterGUI.ps1
If you don't use the .\ beforehand then it thinks you're trying to run a cmdlet.

**Comment by Sycnex** [comment]
Hi, did you download the .zip file, and then extract it? This looks as though the code was either copied and pasted straight from the Github or that the .zip file was not extracted.

**Comment by DrTeeth707** [comment]
Hi,

You nailed it. I originally
![2019-02-24_14h19_02](https://user-images.githubusercontent.com/39297836/53300442-384a4f80-383f-11e9-91e9-b3f48b577e77.png)
 downloaded the file by right-clicking it and "saving as". I really had to look hard to find the zip file.
Thanks for your help, it's much appreciated.

**Comment by Sycnex** [comment]
I’m happy to have helped! I hope the scripts work out for you :)
