### ISSUE TITLE
Live tiles stopped working after using this

### ISSUE THREAD

**Issue by AdamWrighter** [Sycnex/Windows10Debloater#89]
I'm not sure if this actually a result of this script, but on both machines I ran it on, live tiles have since stopped working for all apps. Do you know if this script does anything live tile-related?

**Comment by Sycnex** [comment]
I haven't programmed it to affect live tiles but it could certainly be a side effect of the script. Which script in particular did you use?

**Comment by AdamWrighter** [comment]
Thanks for your reply. I used Windows10Debloater.ps1. I've reinstalled the Mail app, for example, but live tile isn't working for it (and live tile is definitely turned on for that app).

**Comment by samayo** [comment]
This is odd, I have been using this debloater script for quite some time, and I have had always issues with my live tile, not working only when I am using chrome with 10+ tabs. I thought it was an issue with memory  or something like that. Can anyone provide more proof?

**Comment by HetorusNL** [comment]
The removal of live tiles is present in the `Windows10Debloater.ps1` script as shown below (or at least mentioned in the output):

```
#Disables live tiles
Write-Output "Disabling live tiles"
$Live = "HKCU:\SOFTWARE\Policies\Microsoft\Windows\CurrentVersion\PushNotifications"    
If (!(Test-Path $Live)) {      
    New-Item $Live
}
Set-ItemProperty $Live NoTileApplicationNotification -Value 1 
```

This happens in the source code lines 252-258.

**Comment by AdamWrighter** [comment]
@HetorusNL  Oh, thank you. Do you know how I could undo that, without reverting all other changes made by the script?

**Comment by Sycnex** [comment]
Yes, you just change the -Value 1 to -Value 0. Here is the code to do that:

#Disables live tiles Write-Output "Disabling live tiles" $Live = "HKCU:\SOFTWARE\Policies\Microsoft\Windows\CurrentVersion\PushNotifications" If (!(Test-Path $Live)) { New-Item $Live } Set-ItemProperty $Live NoTileApplicationNotification -Value 0

**Comment by Sycnex** [comment]
@UltraHR Please let me know if this has resolved your issue.

**Comment by AdamWrighter** [comment]
@Syncex Just tried this. Yes, that worked - thank you very much 😀
