### ISSUE TITLE
Possible incorrect space in a registry key.

### ISSUE THREAD

**Issue by dhoffman98** [Sycnex/Windows10Debloater#9]
On my system, running Windows 10 Pro - 1709, x64, I am seeing my "CloudContent" reg keys differently than what you have posted in the script.

On lines 108, 263, 265, and 266, you code shows "Cloud Content" with the space.
On my machine, there is no space, instead showing:

"HKLM:\SOFTWARE\Policies\Microsoft\Windows\CloudContent"

**Comment by Sycnex** [comment]
Hello,

I am not seeing the version of the registry key path that you have, but instead the "Cloud Content" I have in my script.

Is the registry key path you have without the space on only that machine or others as well? 

My physical and virtuals are all on the latest Windows 10 Pro, 64-Bit, 1709 version.

**Comment by dhoffman98** [comment]
When I get back home tonight I will pull a registry extract and send you the exact key.

**Comment by dhoffman98** [comment]
OK, so here is the exact key from my registry.... but now I'm not finding it at all in HKLM. I did find one in HKCU though:
[HKEY_CURRENT_USER\Software\Policies\Microsoft\Windows\CloudContent]

This is from an OEM build on a new machine. I'll run a new raw build from the 1709 source on a new VM and pull data from there as well.

**Comment by Sycnex** [comment]
Alright. I will take a look at my Windows 10 Machines and see if I can find the same key in the registry under the HKCU Hive.

Yes, I am going to do that, thanks for the suggestion! I am new to all of this.

**Comment by Sycnex** [comment]
This is now fixed in the latest commit. Thanks for catching that!
