### ISSUE TITLE
Script fails when run

### ISSUE THREAD

**Issue by shufty** [Sycnex/Windows10Debloater#9]
Multiple errors when running script in Powershell.

PS C:\> .\Windows10Debloater.ps1 -Start-Debloat -Remove-Keys -Protect-Privacy -Stop-EdgePDF

Security warning
Run only scripts that you trust. While scripts from the internet can be useful, this script can potentially harm your
computer. If you trust this script, use the Unblock-File cmdlet to allow the script to run without this warning
message. Do you want to run C:\Windows10Debloater.ps1?
[D] Do not run  [R] Run once  [S] Suspend  [?] Help (default is "D"): R
At C:\Windows10Debloater.ps1:132 char:19
+ </a>              </li>
+                   ~
The '<' operator is reserved for future use.
At C:\Windows10Debloater.ps1:136 char:19
+ </a>              </li>
+                   ~
The '<' operator is reserved for future use.
At C:\Windows10Debloater.ps1:141 char:19
+ </a>              </li>
+                   ~
The '<' operator is reserved for future use.
At C:\Windows10Debloater.ps1:146 char:19
+ </a>              </li>
+                   ~
The '<' operator is reserved for future use.
At C:\Windows10Debloater.ps1:150 char:19
+ </a>              </li>
+                   ~
The '<' operator is reserved for future use.
At C:\Windows10Debloater.ps1:2508 char:227
+ ... g:0;display:inline"><input name="utf8" type="hidden" value="&#x2713;" ...
+                                                                 ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double quotation marks ("&") to pass it as part of a string.
At C:\Windows10Debloater.ps1:2511 char:10
+ </form>  </div>
+          ~
The '<' operator is reserved for future use.
At C:\Windows10Debloater.ps1:2527 char:24
+       <li class="mr-3">&copy; 2018 <span title="0.15683s from unicorn ...
+                        ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double quotation marks ("&") to pass it as part of a string.
At C:\Windows10Debloater.ps1:2527 char:36
+       <li class="mr-3">&copy; 2018 <span title="0.15683s from unicorn ...
+                                    ~
The '<' operator is reserved for future use.
At C:\Windows10Debloater.ps1:2527 char:42
+ ...  2018 <span title="0.15683s from unicorn-2504035863-4s1t0">GitHub</sp ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Unexpected token 'title="0.15683s from unicorn-2504035863-4s1t0">GitHub</span>' in expression or statement.
Not all parse errors were reported.  Correct the reported errors and try again.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : RedirectionNotSupported

PS C:\>

**Comment by Sycnex** [comment]
Hi Shufty, 

The Windows10Debloater.ps1 file does not use any of those parameters, but the Windows10SysPrepDebloater.ps1 file does.

The parameters that the Windows10SysPrepDebloater.ps1 uses are as follows:

-SysPrep, -Debloat, and -StopEdgePDF

Please try again with the other file and let me know how it works.

**Comment by Sycnex** [comment]
Any update on this?

**Comment by vaidotaskia** [comment]
Downloaded script today and got multiple errors.

```
PS C:\WINDOWS\system32> f:\Windows10SysPrepDebloater.ps1 -SysPrep -Debloat -StopEdgePDF

Security warning
Run only scripts that you trust. While scripts from the internet can be useful, this script can potentially harm your computer. If you trust
 this script, use the Unblock-File cmdlet to allow the script to run without this warning message. Do you want to run
F:\Windows10SysPrepDebloater.ps1?
[D] Do not run  [R] Run once  [S] Suspend  [?] Help (default is "D"): R
At F:\Windows10SysPrepDebloater.ps1:132 char:19
+ </a>              </li>
+                   ~
The '<' operator is reserved for future use.
At F:\Windows10SysPrepDebloater.ps1:136 char:19
+ </a>              </li>
+                   ~
The '<' operator is reserved for future use.
At F:\Windows10SysPrepDebloater.ps1:141 char:19
+ </a>              </li>
+                   ~
The '<' operator is reserved for future use.
At F:\Windows10SysPrepDebloater.ps1:146 char:19
+ </a>              </li>
+                   ~
The '<' operator is reserved for future use.
At F:\Windows10SysPrepDebloater.ps1:150 char:19
+ </a>              </li>
+                   ~
The '<' operator is reserved for future use.
At F:\Windows10SysPrepDebloater.ps1:1479 char:227
+ ... g:0;display:inline"><input name="utf8" type="hidden" value="&#x2713;" ...
+                                                                 ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double quotation marks ("&") to
pass it as part of a string.
At F:\Windows10SysPrepDebloater.ps1:1482 char:10
+ </form>  </div>
+          ~
The '<' operator is reserved for future use.
At F:\Windows10SysPrepDebloater.ps1:1498 char:24
+       <li class="mr-3">&copy; 2018 <span title="0.24799s from unicorn ...
+                        ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double quotation marks ("&") to
pass it as part of a string.
At F:\Windows10SysPrepDebloater.ps1:1498 char:36
+       <li class="mr-3">&copy; 2018 <span title="0.24799s from unicorn ...
+                                    ~
The '<' operator is reserved for future use.
At F:\Windows10SysPrepDebloater.ps1:1498 char:42
+ ...  2018 <span title="0.24799s from unicorn-1384281968-3f9rq">GitHub</sp ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Unexpected token 'title="0.24799s from unicorn-1384281968-3f9rq">GitHub</span>' in expression or statement.
Not all parse errors were reported.  Correct the reported errors and try again.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : RedirectionNotSupported


```

**Comment by Sycnex** [comment]
Did you run it as an administrator?

**Comment by vaidotaskia** [comment]
Yes.
Win+X
WindowsPowerShell (Admin)

OS build 16299.251

**Comment by sbf-** [comment]
```
The '<' operator is reserved for future use.
At F:\Windows10SysPrepDebloater.ps1:1498 char:42
+ ...  2018 <span title="0.24799s from unicorn-1384281968-3f9rq">GitHub</sp ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Unexpected token 'title="0.24799s from unicorn-1384281968-3f9rq">GitHub</span>' in expression or statement.
```

It looks like you downloaded some HTML page instead of the PS1 script

**Comment by vaidotaskia** [comment]
Thanks,
it was my mistake.
Downloaded html page instead of copy/pasting source to a new file.

--
Vaidotas

**Comment by Sycnex** [comment]
Can I close this if it has been resolved?

**Comment by shufty** [comment]
Yes sorry! I ended up using the other script Windows10SysPrepDebloater.ps1 and it seems to work well! Only problem is that it seems to skip some apps, but that's a different problem I guess. You can close this thanks.
