### ISSUE TITLE
using script breaks .NET and does not allow to install ms office

### ISSUE THREAD

**Issue by lennonenko** [Sycnex/Windows10Debloater#90]
after using that scripts for removing bloatware in windows 10 1809 somehow breaks .NET and further makes installation of ms office 2016 and 2013 impossible (msi errors 1935 and 1603)
this concerns precisely the latest release, previous version was ok with that
workaround is turning off .NET in "optional features"

**Comment by Sycnex** [comment]
I have added a new button in the Windows10DebloaterGUI.ps1 that will ask you if you'd like to install .NET 3.5 since I cannot seem to find the issue as to why my scripts randomly (and rarely) break .NET.

I have also added it as a prompt in the Windows10Debloater.ps1 file.
