### ISSUE TITLE
Windows 10 - GameBar

### ISSUE THREAD

**Issue by smoonlee** [Sycnex/Windows10Debloater#91]
It doesnt look like the Windows 10 Gamebar is removed using the WIndows10SysprepDebloater

**Comment by Sycnex** [comment]
Do the other 2 scripts that I have remove it?

**Comment by smoonlee** [comment]
@Sycnex will try this afternoon i have some time :-)

**Comment by smoonlee** [comment]
@Sycnex  Sorry for the late reply!

I've just executed Windows10Debloater.ps1 on an 1809 Pro VM and the Game Bar is still showing in the start meun

![image](https://user-images.githubusercontent.com/22956963/53810358-aa611980-3f4e-11e9-906a-eb5e43687e2d.png)

**Comment by smoonlee** [comment]
I can confirm that it is removed when using the Sysprep Script and Removing the Following from the WhiteList 

Microsoft.XboxGameCallableUI|Microsoft.XboxGamingOverlay|Microsoft.Xbox.TCUI|Microsoft.XboxGamingOverlay|Microsoft.XboxIdentityProvider

**Comment by Sycnex** [comment]
Ah gotcha, so because it is whitelisted it was staying there. I don't necessarily want to remove those from the code because a lot of average home users use it and did not want anything XBOX related being removed.

**Comment by smoonlee** [comment]
> Ah gotcha, so because it is whitelisted it was staying there. I don't necessarily want to remove those from the code because a lot of average home users use it and did not want anything XBOX related being removed.

Thats Cool - Get that!, Could we create an extra script them for home and enterprise use?
