### ISSUE TITLE
Stop-PDF not functioning

### ISSUE THREAD

**Issue by cdeli** [Sycnex/Windows10Debloater#97]
Running the SysPrepDebloater I get to the end and get "The term stop-edfepdf" is not recognized.

Seems to be no reason for this as all of the files exist for it including in the subfolder. 

I am not using the -SysPrep parameter, I am using -Debloat -Privacy -StopEdgePdf parameters however.

**Comment by cdeli** [comment]
Needed to add the function for the PDF to the script in order for the error to be removed.

**Comment by Sycnex** [comment]
I originally removed that from the Windows10SysPrepDebloater due to people stating that they didn't want it in there.

**Comment by mattreecebentley** [comment]
Then remove it from the documentation too, please.
Currently the StopEdgePDF functionality does not work on any version.

**Comment by Sycnex** [comment]
I have updated the documentation.
